In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_df.csv")

In [7]:
df

,Unnamed: 0,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
0,1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
1,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
3,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
4,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...,...
58583,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
58584,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
58585,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
58586,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
58587,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [16]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split'])['text_cleaned'].sum())

a = a.reset_index()
a

,date_cleaned,topic_split,text_cleaned
0,2007-11-03,armed conflicts and attacks,2007 Pakistani state of emergency President ...
1,2010-06-02,armed conflicts and attacks,The crew of the Libyan M V Rim takes back ...
2,2010-06-02,arts and culture,The crew of the Libyan M V Rim takes back ...
3,2010-06-02,disasters and accidents,The crew of the Libyan M V Rim takes back ...
4,2010-06-02,international relations,The crew of the Libyan M V Rim takes back ...
...,...,...,...
9607,2025-10-06,disasters and accidents,Russo Ukrainian war Crimea attacks Ukraine...
9608,2025-10-06,international relations,Russo Ukrainian war Crimea attacks Ukraine...
9609,2025-10-06,law and crime and politics,Russo Ukrainian war Crimea attacks Ukraine...
9610,2025-10-06,politics and elections and economics,Russo Ukrainian war Crimea attacks Ukraine...
9611,2025-10-06,science and technology,Russo Ukrainian war Crimea attacks Ukraine...

In [24]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split']).text_cleaned.count())
a = a.reset_index()
a = a.rename({"text_cleaned": "count"}, axis=1)
a

     date_cleaned                           topic_split  count
0      2007-11-03           armed conflicts and attacks      1
1      2010-06-02           armed conflicts and attacks      9
2      2010-06-02                      arts and culture     18
3      2010-06-02               disasters and accidents      9
4      2010-06-02               international relations      9
...           ...                                   ...    ...
9607   2025-10-06               disasters and accidents      6
9608   2025-10-06               international relations      6
9609   2025-10-06            law and crime and politics      6
9610   2025-10-06  politics and elections and economics      6
9611   2025-10-06                science and technology      6

[9612 rows x 3 columns]

In [25]:
a.to_csv("news_data_ready_to_plot.csv", index=False)

In [8]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(df.date_cleaned, df.)

In [2]:
import joblib 
import pandas as pd
a = joblib.load("new_df.pkl")
b = pd.read_csv("cleaned_df.csv")

In [6]:
b.groupby(['date', 'text_cleaned']).agg('topic_split'==str('topic_split'), ','.join)

TypeError: 'bool' object is not callable

In [10]:
c = pd.DataFrame(b.groupby(['date', 'text_cleaned'])['topic_split'].agg(','.join))
c = c.reset_index()
c

,date,text_cleaned,topic_split
0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...
1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [11]:
!pwd

/Users/thomasnguyen/news_project/data

In [12]:
c.to_csv("cleaned_df.csv")

In [14]:
len(b.topic_split.unique())

14

# improving the model

Maybe I can use a pretrained transformer model to classify the news articles

In [266]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as stats 
import numpy as np 
import re
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.neighbors import NearestNeighbors
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit
from xgboost import XGBClassifier
from nltk.corpus import stopwords

# ── Data loading & cleaning ───────────────────────────────────────────────────
cleaned_df = pd.read_csv("cleaned_df.csv")
replacements = {
    "culture and entertainment": "other",
    "culture and society": "other",
    ",environment,": ",other,",
    "religion": "other",
    "culture & entertainment": "other",
    "other current events": "other",
    "other and politics": "other",
    ",entertainment": ",other",
}
for old, new in replacements.items():
    cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace(old, new)

cleaned_df = cleaned_df[~cleaned_df.topic_split.str.contains("other", na=False)]

topic_counts = (
    cleaned_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)
print(topic_counts)

# ── Features & labels ─────────────────────────────────────────────────────────
X_raw = cleaned_df.copy()
X_raw['text_cleaned'] = (
    X_raw['text_cleaned']
    .str.replace("[^a-zA-Z0-9.]+", " ", regex=True)
    .str.strip()
    .str.lower()
)

y_lists = cleaned_df['topic_split'].apply(lambda x: [i.strip() for i in x.split(',')])
mlb = MultiLabelBinarizer()
y_mlb = mlb.fit_transform(y_lists)

# ── MLSMOTE ───────────────────────────────────────────────────────────────────
def get_minority_samples(X, y):
    label_counts = y.sum(axis=0)
    mean_ir = np.mean(label_counts)
    minority_labels = np.where(label_counts < mean_ir)[0]
    minority_mask = y[:, minority_labels].sum(axis=1) > 0
    return X[minority_mask], y[minority_mask]

def mlsmote(X, y, n_samples=500, k_neighbors=5, random_state=42):
    rng = np.random.default_rng(random_state)
    X_min, y_min = get_minority_samples(X, y)

    if len(X_min) < k_neighbors + 1:
        print(f"Warning: only {len(X_min)} minority samples, reducing k")
        k_neighbors = len(X_min) - 1

    knn = NearestNeighbors(n_neighbors=k_neighbors + 1)
    knn.fit(X_min)

    synthetic_X, synthetic_y = [], []
    for _ in range(n_samples):
        idx = rng.integers(0, len(X_min))
        x_ref, y_ref = X_min[idx], y_min[idx]
        _, neighbor_idxs = knn.kneighbors([x_ref])
        nn_idx = rng.choice(neighbor_idxs[0][1:])
        x_neighbor, y_neighbor = X_min[nn_idx], y_min[nn_idx]
        gap = rng.random()
        x_synthetic = x_ref + gap * (x_neighbor - x_ref)
        y_synthetic = np.logical_or(y_ref, y_neighbor).astype(int)
        synthetic_X.append(x_synthetic)
        synthetic_y.append(y_synthetic)

    return (
        np.vstack([X, np.array(synthetic_X)]),
        np.vstack([y, np.array(synthetic_y)])
    )

# ── FIX 1: Split RAW TEXT first, before any vectorisation ────────────────────
stop_words = list(set(stopwords.words('english')))

splitter = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in splitter.split(X_raw, y_mlb):
    X_train_text = X_raw['text_cleaned'].iloc[train_idx]
    X_test_text  = X_raw['text_cleaned'].iloc[test_idx]
    y_train      = y_mlb[train_idx]
    y_test       = y_mlb[test_idx]

# FIX 2: Fit vectoriser ONLY on training text, then transform both splits
vectorizer = TfidfVectorizer(
    max_features=5000,   # FIX 3: reduced from 10000 to limit dimensionality
    stop_words=stop_words,
    lowercase=True,
    min_df=10,
    strip_accents='unicode'
)
X_train = vectorizer.fit_transform(X_train_text).toarray()
X_test  = vectorizer.transform(X_test_text).toarray()   # transform only — no fit

# ── MLSMOTE on training data only ────────────────────────────────────────────
X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

before = y_train.sum(axis=0)
after  = y_train_res.sum(axis=0)
print(pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_))

# ── FIX 4: XGBoost with regularisation, and use resampled data ───────────────
print ("Creating the model...")
model = MultiOutputClassifier(
    XGBClassifier(

    )
)

model.fit(X_train_res, y_train_res)  # FIX 9: was using Y_train (typo) and non-resampled data

topic_split
armed conflicts and attacks             1587
law and crime and politics              1389
disasters and accidents                 1374
politics and elections and economics    1198
international relations                 1035
health and environment                   813
business and economics                   671
sports                                   596
science and technology                   462
arts and culture                         344
Name: count, dtype: int64
Before: 1327 samples
After:  1627 samples
                                      before  after
armed conflicts and attacks             1263   1562
arts and culture                         275    405
business and economics                   537    743
disasters and accidents                 1095   1376
health and environment                   650    859
international relations                  828   1088
law and crime and politics              1111   1405
politics and elections and economics     958   1231
science and technology                   370    507
sports                                   477    667
Creating the model...

MultiOutputClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=None,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=False,
                                              eval_metric=None,
                                              feature_types=None,
                                              feature_weights=None, gamma=None,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=None, max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None,
                                              max_depth=None, max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=None, n_jobs=None,
                                              num_parallel_tree=None, ...))

In [267]:
pred = model.predict(X_test)
train_pred = model.predict(X_train_res)

In [268]:
pred

array([[1, 0, 0, ..., 0, 1, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 1]])

In [269]:
np.unique(train_pred == y_train_res)

array([ True])

# metrics

In [270]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_curve, confusion_matrix, ConfusionMatrixDisplay

In [271]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()

In [272]:
MR

0.18421052631578946

In [273]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [274]:
loss01

0.8157894736842105

In [275]:
accuracy_score(pred, y_test)

0.18421052631578946

In [276]:
accuracy_score(train_pred, y_train_res)

1.0

In [277]:
f1_score(y_test, pred, average='micro')

0.8544825751529662

In [278]:
from sklearn.metrics import f1_score
f1_score(y_test, pred, average='macro')

0.7715211906810745

In [279]:
f1_score(y_pred=train_pred, y_true=y_train_res, average='macro')

1.0

In [280]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

0.8419121360675694

In [281]:
from sklearn.model_selection import cross_val_score

In [282]:
# tuning the model

In [283]:
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer
from sklearn.metrics import hamming_loss

In [284]:
X_train_res

array([[0.0755931 , 0.10651944, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.02303957, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.00995367, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.02176478,
        0.        ]])

In [285]:
y_train_res

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 0],
       [1, 1, 0, ..., 1, 0, 1]])

In [287]:
# bayesian search

from iterstrat.ml_stratifiers import MultilabelStratifiedKFold
from sklearn.multioutput import ClassifierChain
cv_splitter = MultilabelStratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Run grid search
opt = BayesSearchCV(
    estimator=ClassifierChain(XGBClassifier()),

    

    search_spaces={
        'estimator__n_estimators': Integer(10, 50),

        'estimator__max_depth': Integer(10, 70),
        'estimator__lambda': Integer(1, 30),
        "estimator__eta": Real(0.1, 0.3)
    },
    n_iter=32,
    cv=cv_splitter,
    scoring='f1_macro',
    return_train_score=True,  # use macro F1 for imbalanced multilabel
    n_jobs=-1,                # use all CPU cores
    verbose=3
)

opt.fit(X_train_res, y_train_res)

Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.2246980239562067, estimator__lambda=19, estimator__max_depth=46, estimator__n_estimators=37;, score=(train=1.000, test=0.831) total time= 2.5min
[CV 5/5] END estimator__eta=0.2246980239562067, estimator__lambda=19, estimator__max_depth=46, estimator__n_estimators=37;, score=(train=1.000, test=0.827) total time= 2.5min
[CV 1/5] END estimator__eta=0.2246980239562067, estimator__lambda=19, estimator__max_depth=46, estimator__n_estimators=37;, score=(train=1.000, test=0.826) total time= 2.5min
[CV 3/5] END estimator__eta=0.2246980239562067, estimator__lambda=19, estimator__max_depth=46, estimator__n_estimators=37;, score=(train=1.000, test=0.828) total time= 2.5min
[CV 2/5] END estimator__eta=0.2246980239562067, estimator__lambda=19, estimator__max_depth=46, estimator__n_estimators=37;, score=(train=1.000, test=0.842) total time= 2.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.24663245407063214, estimator__lambda=4, estimator__max_depth=18, estimator__n_estimators=20;, score=(train=1.000, test=0.841) total time= 1.3min
[CV 5/5] END estimator__eta=0.24663245407063214, estimator__lambda=4, estimator__max_depth=18, estimator__n_estimators=20;, score=(train=1.000, test=0.844) total time= 1.3min
[CV 3/5] END estimator__eta=0.24663245407063214, estimator__lambda=4, estimator__max_depth=18, estimator__n_estimators=20;, score=(train=1.000, test=0.833) total time= 1.3min
[CV 2/5] END estimator__eta=0.24663245407063214, estimator__lambda=4, estimator__max_depth=18, estimator__n_estimators=20;, score=(train=1.000, test=0.838) total time= 1.3min
[CV 1/5] END estimator__eta=0.24663245407063214, estimator__lambda=4, estimator__max_depth=18, estimator__n_estimators=20;, score=(train=1.000, test=0.829) total time= 1.3min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.25381534962671337, estimator__lambda=1, estimator__max_depth=66, estimator__n_estimators=40;, score=(train=1.000, test=0.851) total time= 1.6min
[CV 1/5] END estimator__eta=0.25381534962671337, estimator__lambda=1, estimator__max_depth=66, estimator__n_estimators=40;, score=(train=1.000, test=0.839) total time= 1.6min
[CV 3/5] END estimator__eta=0.25381534962671337, estimator__lambda=1, estimator__max_depth=66, estimator__n_estimators=40;, score=(train=1.000, test=0.852) total time= 1.6min
[CV 5/5] END estimator__eta=0.25381534962671337, estimator__lambda=1, estimator__max_depth=66, estimator__n_estimators=40;, score=(train=1.000, test=0.852) total time= 1.6min
[CV 2/5] END estimator__eta=0.25381534962671337, estimator__lambda=1, estimator__max_depth=66, estimator__n_estimators=40;, score=(train=1.000, test=0.850) total time= 1.6min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.2214323923041127, estimator__lambda=26, estimator__max_depth=48, estimator__n_estimators=25;, score=(train=0.997, test=0.815) total time= 1.8min
[CV 3/5] END estimator__eta=0.2214323923041127, estimator__lambda=26, estimator__max_depth=48, estimator__n_estimators=25;, score=(train=0.997, test=0.816) total time= 1.8min
[CV 5/5] END estimator__eta=0.2214323923041127, estimator__lambda=26, estimator__max_depth=48, estimator__n_estimators=25;, score=(train=0.997, test=0.818) total time= 1.8min
[CV 1/5] END estimator__eta=0.2214323923041127, estimator__lambda=26, estimator__max_depth=48, estimator__n_estimators=25;, score=(train=0.997, test=0.815) total time= 1.8min
[CV 2/5] END estimator__eta=0.2214323923041127, estimator__lambda=26, estimator__max_depth=48, estimator__n_estimators=25;, score=(train=0.997, test=0.840) total time= 1.8min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.27761579264057945, estimator__lambda=2, estimator__max_depth=27, estimator__n_estimators=31;, score=(train=1.000, test=0.853) total time= 1.4min
[CV 3/5] END estimator__eta=0.27761579264057945, estimator__lambda=2, estimator__max_depth=27, estimator__n_estimators=31;, score=(train=1.000, test=0.848) total time= 1.4min
[CV 1/5] END estimator__eta=0.27761579264057945, estimator__lambda=2, estimator__max_depth=27, estimator__n_estimators=31;, score=(train=1.000, test=0.838) total time= 1.4min
[CV 5/5] END estimator__eta=0.27761579264057945, estimator__lambda=2, estimator__max_depth=27, estimator__n_estimators=31;, score=(train=1.000, test=0.844) total time= 1.4min
[CV 2/5] END estimator__eta=0.27761579264057945, estimator__lambda=2, estimator__max_depth=27, estimator__n_estimators=31;, score=(train=1.000, test=0.849) total time= 1.4min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END estimator__eta=0.2898735690898823, estimator__lambda=10, estimator__max_depth=59, estimator__n_estimators=22;, score=(train=1.000, test=0.831) total time= 1.5min
[CV 5/5] END estimator__eta=0.2898735690898823, estimator__lambda=10, estimator__max_depth=59, estimator__n_estimators=22;, score=(train=1.000, test=0.836) total time= 1.5min
[CV 3/5] END estimator__eta=0.2898735690898823, estimator__lambda=10, estimator__max_depth=59, estimator__n_estimators=22;, score=(train=1.000, test=0.836) total time= 1.5min
[CV 4/5] END estimator__eta=0.2898735690898823, estimator__lambda=10, estimator__max_depth=59, estimator__n_estimators=22;, score=(train=1.000, test=0.835) total time= 1.5min
[CV 2/5] END estimator__eta=0.2898735690898823, estimator__lambda=10, estimator__max_depth=59, estimator__n_estimators=22;, score=(train=1.000, test=0.840) total time= 1.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.16904242071342432, estimator__lambda=18, estimator__max_depth=23, estimator__n_estimators=23;, score=(train=0.994, test=0.818) total time= 1.7min
[CV 3/5] END estimator__eta=0.16904242071342432, estimator__lambda=18, estimator__max_depth=23, estimator__n_estimators=23;, score=(train=0.994, test=0.818) total time= 1.7min
[CV 5/5] END estimator__eta=0.16904242071342432, estimator__lambda=18, estimator__max_depth=23, estimator__n_estimators=23;, score=(train=0.994, test=0.807) total time= 1.7min
[CV 1/5] END estimator__eta=0.16904242071342432, estimator__lambda=18, estimator__max_depth=23, estimator__n_estimators=23;, score=(train=0.994, test=0.809) total time= 1.7min
[CV 2/5] END estimator__eta=0.16904242071342432, estimator__lambda=18, estimator__max_depth=23, estimator__n_estimators=23;, score=(train=0.994, test=0.824) total time= 1.7min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.18269566180040855, estimator__lambda=23, estimator__max_depth=38, estimator__n_estimators=13;, score=(train=0.956, test=0.792) total time= 1.1min
[CV 5/5] END estimator__eta=0.18269566180040855, estimator__lambda=23, estimator__max_depth=38, estimator__n_estimators=13;, score=(train=0.959, test=0.777) total time= 1.1min
[CV 3/5] END estimator__eta=0.18269566180040855, estimator__lambda=23, estimator__max_depth=38, estimator__n_estimators=13;, score=(train=0.955, test=0.790) total time= 1.1min
[CV 1/5] END estimator__eta=0.18269566180040855, estimator__lambda=23, estimator__max_depth=38, estimator__n_estimators=13;, score=(train=0.955, test=0.775) total time= 1.1min
[CV 2/5] END estimator__eta=0.18269566180040855, estimator__lambda=23, estimator__max_depth=38, estimator__n_estimators=13;, score=(train=0.957, test=0.799) total time= 1.1min
Fitting 5 folds for each of 1 candidates, totalling 5 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x1033cd940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 4/5] END estimator__eta=0.10624776500818378, estimator__lambda=4, estimator__max_depth=64, estimator__n_estimators=38;, score=(train=1.000, test=0.839) total time= 3.8min
[CV 1/5] END estimator__eta=0.10624776500818378, estimator__lambda=4, estimator__max_depth=64, estimator__n_estimators=38;, score=(train=1.000, test=0.832) total time= 3.8min
[CV 3/5] END estimator__eta=0.10624776500818378, estimator__lambda=4, estimator__max_depth=64, estimator__n_estimators=38;, score=(train=1.000, test=0.846) total time= 3.8min
[CV 5/5] END estimator__eta=0.10624776500818378, estimator__lambda=4, estimator__max_depth=64, estimator__n_estimators=38;, score=(train=1.000, test=0.841) total time= 3.8min
[CV 2/5] END estimator__eta=0.10624776500818378, estimator__lambda=4, estimator__max_depth=64, estimator__n_estimators=38;, score=(train=1.000, test=0.842) total time= 3.8min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.12667176158225713, estimator__lambda=30, estimator__max_depth=38, estimator__n_estimators=10;, score=(train=0.819, test=0.741) total time=  49.9s
[CV 5/5] END estimator__eta=0.12667176158225713, estimator__lambda=30, estimator__max_depth=38, estimator__n_estimators=10;, score=(train=0.841, test=0.737) total time=  51.6s
[CV 3/5] END estimator__eta=0.12667176158225713, estimator__lambda=30, estimator__max_depth=38, estimator__n_estimators=10;, score=(train=0.829, test=0.743) total time=  51.8s
[CV 1/5] END estimator__eta=0.12667176158225713, estimator__lambda=30, estimator__max_depth=38, estimator__n_estimators=10;, score=(train=0.823, test=0.733) total time=  52.0s
[CV 2/5] END estimator__eta=0.12667176158225713, estimator__lambda=30, estimator__max_depth=38, estimator__n_estimators=10;, score=(train=0.829, test=0.755) total time=  52.1s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.13191115523458521, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.846) total time= 2.7min
[CV 3/5] END estimator__eta=0.13191115523458521, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.847) total time= 2.7min
[CV 5/5] END estimator__eta=0.13191115523458521, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.839) total time= 2.7min
[CV 2/5] END estimator__eta=0.13191115523458521, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.849) total time= 2.7min
[CV 1/5] END estimator__eta=0.13191115523458521, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.843) total time= 2.7min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 3/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.846) total time= 1.2min
[CV 4/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.851) total time= 1.2min
[CV 5/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.840) total time= 1.2min
[CV 1/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.840) total time= 1.2min
[CV 2/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=50;, score=(train=1.000, test=0.845) total time= 1.3min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 3/5] END estimator__eta=0.18048455470024008, estimator__lambda=1, estimator__max_depth=12, estimator__n_estimators=37;, score=(train=1.000, test=0.850) total time= 1.5min
[CV 5/5] END estimator__eta=0.18048455470024008, estimator__lambda=1, estimator__max_depth=12, estimator__n_estimators=37;, score=(train=1.000, test=0.850) total time= 1.5min
[CV 4/5] END estimator__eta=0.18048455470024008, estimator__lambda=1, estimator__max_depth=12, estimator__n_estimators=37;, score=(train=1.000, test=0.846) total time= 1.5min
[CV 1/5] END estimator__eta=0.18048455470024008, estimator__lambda=1, estimator__max_depth=12, estimator__n_estimators=37;, score=(train=1.000, test=0.836) total time= 1.5min
[CV 2/5] END estimator__eta=0.18048455470024008, estimator__lambda=1, estimator__max_depth=12, estimator__n_estimators=37;, score=(train=1.000, test=0.848) total time= 1.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.1027178420839261, estimator__lambda=30, estimator__max_depth=49, estimator__n_estimators=50;, score=(train=0.995, test=0.815) total time= 4.3min
[CV 5/5] END estimator__eta=0.1027178420839261, estimator__lambda=30, estimator__max_depth=49, estimator__n_estimators=50;, score=(train=0.995, test=0.815) total time= 4.3min
[CV 3/5] END estimator__eta=0.1027178420839261, estimator__lambda=30, estimator__max_depth=49, estimator__n_estimators=50;, score=(train=0.995, test=0.821) total time= 4.4min
[CV 1/5] END estimator__eta=0.1027178420839261, estimator__lambda=30, estimator__max_depth=49, estimator__n_estimators=50;, score=(train=0.996, test=0.810) total time= 4.4min
[CV 2/5] END estimator__eta=0.1027178420839261, estimator__lambda=30, estimator__max_depth=49, estimator__n_estimators=50;, score=(train=0.996, test=0.827) total time= 4.4min
Fitting 5 folds for each of 1 candidates, totalling 5 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x102edd940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 1/5] END estimator__eta=0.2249836503438194, estimator__lambda=1, estimator__max_depth=61, estimator__n_estimators=50;, score=(train=1.000, test=0.842) total time= 1.9min
[CV 5/5] END estimator__eta=0.2249836503438194, estimator__lambda=1, estimator__max_depth=61, estimator__n_estimators=50;, score=(train=1.000, test=0.856) total time= 1.9min
[CV 3/5] END estimator__eta=0.2249836503438194, estimator__lambda=1, estimator__max_depth=61, estimator__n_estimators=50;, score=(train=1.000, test=0.850) total time= 1.9min
[CV 4/5] END estimator__eta=0.2249836503438194, estimator__lambda=1, estimator__max_depth=61, estimator__n_estimators=50;, score=(train=1.000, test=0.854) total time= 1.9min
[CV 2/5] END estimator__eta=0.2249836503438194, estimator__lambda=1, estimator__max_depth=61, estimator__n_estimators=50;, score=(train=1.000, test=0.858) total time= 1.9min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 5/5] END estimator__eta=0.29957880178732255, estimator__lambda=2, estimator__max_depth=55, estimator__n_estimators=10;, score=(train=0.999, test=0.839) total time=  47.8s
[CV 1/5] END estimator__eta=0.29957880178732255, estimator__lambda=2, estimator__max_depth=55, estimator__n_estimators=10;, score=(train=0.999, test=0.820) total time=  48.0s
[CV 4/5] END estimator__eta=0.29957880178732255, estimator__lambda=2, estimator__max_depth=55, estimator__n_estimators=10;, score=(train=1.000, test=0.834) total time=  48.0s
[CV 3/5] END estimator__eta=0.29957880178732255, estimator__lambda=2, estimator__max_depth=55, estimator__n_estimators=10;, score=(train=0.999, test=0.830) total time=  48.1s
[CV 2/5] END estimator__eta=0.29957880178732255, estimator__lambda=2, estimator__max_depth=55, estimator__n_estimators=10;, score=(train=1.000, test=0.842) total time=  48.1s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 5/5] END estimator__eta=0.21581254366380126, estimator__lambda=1, estimator__max_depth=65, estimator__n_estimators=28;, score=(train=1.000, test=0.853) total time= 1.5min
[CV 1/5] END estimator__eta=0.21581254366380126, estimator__lambda=1, estimator__max_depth=65, estimator__n_estimators=28;, score=(train=1.000, test=0.840) total time= 1.6min
[CV 3/5] END estimator__eta=0.21581254366380126, estimator__lambda=1, estimator__max_depth=65, estimator__n_estimators=28;, score=(train=1.000, test=0.851) total time= 1.6min
[CV 4/5] END estimator__eta=0.21581254366380126, estimator__lambda=1, estimator__max_depth=65, estimator__n_estimators=28;, score=(train=1.000, test=0.852) total time= 1.5min
[CV 2/5] END estimator__eta=0.21581254366380126, estimator__lambda=1, estimator__max_depth=65, estimator__n_estimators=28;, score=(train=1.000, test=0.848) total time= 1.6min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.2892888312524654, estimator__lambda=27, estimator__max_depth=54, estimator__n_estimators=50;, score=(train=1.000, test=0.840) total time= 2.9min
[CV 1/5] END estimator__eta=0.2892888312524654, estimator__lambda=27, estimator__max_depth=54, estimator__n_estimators=50;, score=(train=1.000, test=0.827) total time= 2.9min
[CV 3/5] END estimator__eta=0.2892888312524654, estimator__lambda=27, estimator__max_depth=54, estimator__n_estimators=50;, score=(train=1.000, test=0.830) total time= 2.9min
[CV 5/5] END estimator__eta=0.2892888312524654, estimator__lambda=27, estimator__max_depth=54, estimator__n_estimators=50;, score=(train=1.000, test=0.832) total time= 2.9min
[CV 2/5] END estimator__eta=0.2892888312524654, estimator__lambda=27, estimator__max_depth=54, estimator__n_estimators=50;, score=(train=1.000, test=0.847) total time= 2.9min
Fitting 5 folds for each of 1 candidates, totalling 5 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x104f49940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 4/5] END estimator__eta=0.1842023168897382, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.853) total time= 2.5min
[CV 5/5] END estimator__eta=0.1842023168897382, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.849) total time= 2.5min
[CV 3/5] END estimator__eta=0.1842023168897382, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.848) total time= 2.5min
[CV 1/5] END estimator__eta=0.1842023168897382, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.839) total time= 2.5min
[CV 2/5] END estimator__eta=0.1842023168897382, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.858) total time= 2.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.10842892723877942, estimator__lambda=1, estimator__max_depth=46, estimator__n_estimators=29;, score=(train=1.000, test=0.841) total time= 2.5min
[CV 5/5] END estimator__eta=0.10842892723877942, estimator__lambda=1, estimator__max_depth=46, estimator__n_estimators=29;, score=(train=1.000, test=0.840) total time= 2.5min
[CV 1/5] END estimator__eta=0.10842892723877942, estimator__lambda=1, estimator__max_depth=46, estimator__n_estimators=29;, score=(train=1.000, test=0.835) total time= 2.5min
[CV 3/5] END estimator__eta=0.10842892723877942, estimator__lambda=1, estimator__max_depth=46, estimator__n_estimators=29;, score=(train=1.000, test=0.840) total time= 2.5min
[CV 2/5] END estimator__eta=0.10842892723877942, estimator__lambda=1, estimator__max_depth=46, estimator__n_estimators=29;, score=(train=1.000, test=0.849) total time= 2.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 5/5] END estimator__eta=0.24623087183570874, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.850) total time= 1.9min
[CV 3/5] END estimator__eta=0.24623087183570874, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.851) total time= 1.9min
[CV 4/5] END estimator__eta=0.24623087183570874, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.851) total time= 1.9min
[CV 1/5] END estimator__eta=0.24623087183570874, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.841) total time= 1.9min
[CV 2/5] END estimator__eta=0.24623087183570874, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.855) total time= 1.9min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 5/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=29;, score=(train=1.000, test=0.848) total time= 1.4min
[CV 4/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=29;, score=(train=1.000, test=0.852) total time= 1.4min
[CV 3/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=29;, score=(train=1.000, test=0.846) total time= 1.4min
[CV 1/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=29;, score=(train=1.000, test=0.832) total time= 1.3min
[CV 2/5] END estimator__eta=0.3, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=29;, score=(train=1.000, test=0.854) total time= 1.4min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.21999371897817815, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.854) total time= 2.0min
[CV 5/5] END estimator__eta=0.21999371897817815, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.848) total time= 2.0min
[CV 1/5] END estimator__eta=0.21999371897817815, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.835) total time= 2.0min
[CV 3/5] END estimator__eta=0.21999371897817815, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.858) total time= 2.0min
[CV 2/5] END estimator__eta=0.21999371897817815, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.854) total time= 2.0min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.22762202352020025, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=33;, score=(train=1.000, test=0.846) total time= 1.7min
[CV 5/5] END estimator__eta=0.22762202352020025, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=33;, score=(train=1.000, test=0.845) total time= 1.7min
[CV 1/5] END estimator__eta=0.22762202352020025, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=33;, score=(train=1.000, test=0.834) total time= 1.7min
[CV 3/5] END estimator__eta=0.22762202352020025, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=33;, score=(train=1.000, test=0.852) total time= 1.7min
[CV 2/5] END estimator__eta=0.22762202352020025, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=33;, score=(train=1.000, test=0.852) total time= 1.7min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.2954374869196199, estimator__lambda=30, estimator__max_depth=26, estimator__n_estimators=31;, score=(train=0.999, test=0.827) total time= 2.6min
[CV 1/5] END estimator__eta=0.2954374869196199, estimator__lambda=30, estimator__max_depth=26, estimator__n_estimators=31;, score=(train=0.999, test=0.820) total time= 2.6min
[CV 5/5] END estimator__eta=0.2954374869196199, estimator__lambda=30, estimator__max_depth=26, estimator__n_estimators=31;, score=(train=0.999, test=0.826) total time= 2.6min
[CV 3/5] END estimator__eta=0.2954374869196199, estimator__lambda=30, estimator__max_depth=26, estimator__n_estimators=31;, score=(train=0.999, test=0.823) total time= 2.6min
[CV 2/5] END estimator__eta=0.2954374869196199, estimator__lambda=30, estimator__max_depth=26, estimator__n_estimators=31;, score=(train=0.999, test=0.843) total time= 2.6min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.21842522842461792, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=47;, score=(train=1.000, test=0.855) total time= 2.1min
[CV 1/5] END estimator__eta=0.21842522842461792, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=47;, score=(train=1.000, test=0.835) total time= 2.1min
[CV 5/5] END estimator__eta=0.21842522842461792, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=47;, score=(train=1.000, test=0.855) total time= 2.1min
[CV 3/5] END estimator__eta=0.21842522842461792, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=47;, score=(train=1.000, test=0.859) total time= 2.1min
[CV 2/5] END estimator__eta=0.21842522842461792, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=47;, score=(train=1.000, test=0.860) total time= 2.1min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.222091588357478, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=46;, score=(train=1.000, test=0.855) total time= 1.5min
[CV 5/5] END estimator__eta=0.222091588357478, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=46;, score=(train=1.000, test=0.845) total time= 1.5min
[CV 3/5] END estimator__eta=0.222091588357478, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=46;, score=(train=1.000, test=0.846) total time= 1.5min
[CV 1/5] END estimator__eta=0.222091588357478, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=46;, score=(train=1.000, test=0.830) total time= 1.5min
[CV 2/5] END estimator__eta=0.222091588357478, estimator__lambda=1, estimator__max_depth=10, estimator__n_estimators=46;, score=(train=1.000, test=0.853) total time= 1.5min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.20704277195639528, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.854) total time= 2.0min
[CV 5/5] END estimator__eta=0.20704277195639528, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.853) total time= 2.0min
[CV 3/5] END estimator__eta=0.20704277195639528, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.851) total time= 2.0min
[CV 1/5] END estimator__eta=0.20704277195639528, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.839) total time= 2.0min
[CV 2/5] END estimator__eta=0.20704277195639528, estimator__lambda=1, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.850) total time= 2.1min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 3/5] END estimator__eta=0.10992836832943396, estimator__lambda=2, estimator__max_depth=62, estimator__n_estimators=10;, score=(train=0.969, test=0.824) total time=  54.5s
[CV 5/5] END estimator__eta=0.10992836832943396, estimator__lambda=2, estimator__max_depth=62, estimator__n_estimators=10;, score=(train=0.966, test=0.811) total time=  54.5s
[CV 4/5] END estimator__eta=0.10992836832943396, estimator__lambda=2, estimator__max_depth=62, estimator__n_estimators=10;, score=(train=0.966, test=0.815) total time=  54.6s
[CV 1/5] END estimator__eta=0.10992836832943396, estimator__lambda=2, estimator__max_depth=62, estimator__n_estimators=10;, score=(train=0.970, test=0.812) total time=  54.7s
[CV 2/5] END estimator__eta=0.10992836832943396, estimator__lambda=2, estimator__max_depth=62, estimator__n_estimators=10;, score=(train=0.971, test=0.822) total time=  54.9s
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 1/5] END estimator__eta=0.2765781523071602, estimator__lambda=9, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.834) total time= 2.3min
[CV 5/5] END estimator__eta=0.2765781523071602, estimator__lambda=9, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.848) total time= 2.3min
[CV 3/5] END estimator__eta=0.2765781523071602, estimator__lambda=9, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.839) total time= 2.3min
[CV 4/5] END estimator__eta=0.2765781523071602, estimator__lambda=9, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.845) total time= 2.3min
[CV 2/5] END estimator__eta=0.2765781523071602, estimator__lambda=9, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.844) total time= 2.3min
Fitting 5 folds for each of 1 candidates, totalling 5 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x102c11940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV 3/5] END estimator__eta=0.15453695745539175, estimator__lambda=12, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.832) total time= 3.3min
[CV 4/5] END estimator__eta=0.15453695745539175, estimator__lambda=12, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.842) total time= 3.3min
[CV 5/5] END estimator__eta=0.15453695745539175, estimator__lambda=12, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.830) total time= 3.3min
[CV 1/5] END estimator__eta=0.15453695745539175, estimator__lambda=12, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.832) total time= 3.3min
[CV 2/5] END estimator__eta=0.15453695745539175, estimator__lambda=12, estimator__max_depth=70, estimator__n_estimators=50;, score=(train=1.000, test=0.844) total time= 3.3min
Fitting 5 folds for each of 1 candidates, totalling 5 fits
[CV 4/5] END estimator__eta=0.11634958174879223, estimator__lambda=1, estimator__max_depth=67, estimator__n_estimators=50;, score=(train=1.000, test=0.845) total time= 3.0min
[CV 5/5] END estimator__eta=0.11634958174879223, estimator__lambda=1, estimator__max_depth=67, estimator__n_estimators=50;, score=(train=1.000, test=0.850) total time= 3.0min
[CV 1/5] END estimator__eta=0.11634958174879223, estimator__lambda=1, estimator__max_depth=67, estimator__n_estimators=50;, score=(train=1.000, test=0.838) total time= 3.0min
[CV 3/5] END estimator__eta=0.11634958174879223, estimator__lambda=1, estimator__max_depth=67, estimator__n_estimators=50;, score=(train=1.000, test=0.852) total time= 3.0min
[CV 2/5] END estimator__eta=0.11634958174879223, estimator__lambda=1, estimator__max_depth=67, estimator__n_estimators=50;, score=(train=1.000, test=0.850) total time= 3.0min

BayesSearchCV(cv=MultilabelStratifiedKFold(n_splits=5, random_state=42, shuffle=True),
              estimator=ClassifierChain(estimator=XGBClassifier(base_score=None,
                                                                booster=None,
                                                                callbacks=None,
                                                                colsample_bylevel=None,
                                                                colsample_bynode=None,
                                                                colsample_bytree=None,
                                                                device=None,
                                                                early_stopping_rounds=None,
                                                                enable_categorical=False,
                                                                eval_metric=None,
                                                                feature_types=None,
                                                                featu...
              search_spaces={'estimator__eta': Real(low=0.1, high=0.3, prior='uniform', transform='normalize'),
                             'estimator__lambda': Integer(low=1, high=30, prior='uniform', transform='normalize'),
                             'estimator__max_depth': Integer(low=10, high=70, prior='uniform', transform='normalize'),
                             'estimator__n_estimators': Integer(low=10, high=50, prior='uniform', transform='normalize')},
              verbose=3)

In [290]:
opt.best_score_

0.852811558716714

In [251]:
from sklearn.metrics import classification_report
print(classification_report(y_test, opt.predict(X_test), target_names=mlb.classes_))

                                      precision    recall  f1-score   support

         armed conflicts and attacks       0.96      0.99      0.97       324
                    arts and culture       0.77      0.29      0.42        69
              business and economics       0.74      0.65      0.69       134
             disasters and accidents       0.86      0.98      0.91       279
              health and environment       0.94      0.80      0.86       163
             international relations       0.87      0.87      0.87       207
          law and crime and politics       0.84      0.96      0.90       278
politics and elections and economics       0.84      0.85      0.85       240
              science and technology       0.83      0.42      0.56        92
                              sports       0.85      0.82      0.83       119

                           micro avg       0.87      0.85      0.86      1905
                           macro avg       0.85      0.76      0.79      1905
                        weighted avg       0.87      0.85      0.85      1905
                         samples avg       0.87      0.86      0.85      1905

In [288]:
print(classification_report(y_test, opt.predict(X_test), target_names=mlb.classes_))

                                      precision    recall  f1-score   support

         armed conflicts and attacks       0.96      0.99      0.97       324
                    arts and culture       0.63      0.25      0.35        69
              business and economics       0.72      0.68      0.70       134
             disasters and accidents       0.87      0.98      0.92       279
              health and environment       0.94      0.79      0.86       163
             international relations       0.87      0.86      0.87       207
          law and crime and politics       0.84      0.95      0.90       278
politics and elections and economics       0.84      0.89      0.86       240
              science and technology       0.81      0.42      0.56        92
                              sports       0.87      0.83      0.85       119

                           micro avg       0.87      0.85      0.86      1905
                           macro avg       0.83      0.76      0.78      1905
                        weighted avg       0.86      0.85      0.85      1905
                         samples avg       0.87      0.86      0.85      1905

In [292]:
import joblib
joblib.dump(opt, '../models/news_topic_classifier/news_topic_classifier.pkl')
joblib.dump(vectorizer, '../models/news_topic_classifier/tfidf_vectorizer.pkl')
joblib.dump(mlb, '../models/news_topic_classifier/mlb.pkl')

['../models/news_topic_classifier/mlb.pkl']

In [103]:
from sklearn.metrics import hamming_loss, label_ranking_loss

In [291]:
pred = opt.predict(X_test)
print (f"accuracy: {accuracy_score(y_true=y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=y_test, average='macro')}")
print (f"hamming loss: {hamming_loss(y_true=y_test, y_pred=pred)}")

accuracy: 0.19005847953216373
f1 score weighted: 0.8489063619056035
f1 score micro: 0.8596352101506741
f1 score macro: 0.7833722316636764
hamming loss: 0.15526315789473685

In [105]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()
MR

0.21052631578947367

In [176]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [177]:
loss01

0.783625730994152

In [ ]:
import joblib 
joblib.dump(grid_search, '../models/news_topic_classifier/news_topic_classifier.pkl')

['../models/news_topic_classifier.pkl']

In [ ]:
joblib.dump(mlb, "../models/news_topic_classifier/mlb.pkl")

['../models/mlb.pkl']

In [ ]:
joblib.dump(vectorizer, '../models/news_topic_classifier/tfidf_vectorizer.pkl')

['../models/tfidf_vectorizer.pkl']

# trying a neural network

In [14]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
import joblib