In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_df.csv")

In [7]:
df

,Unnamed: 0,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
0,1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
1,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
3,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
4,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...,...
58583,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
58584,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
58585,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
58586,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
58587,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [16]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split'])['text_cleaned'].sum())

a = a.reset_index()
a

,date_cleaned,topic_split,text_cleaned
0,2007-11-03,armed conflicts and attacks,2007 Pakistani state of emergency President ...
1,2010-06-02,armed conflicts and attacks,The crew of the Libyan M V Rim takes back ...
2,2010-06-02,arts and culture,The crew of the Libyan M V Rim takes back ...
3,2010-06-02,disasters and accidents,The crew of the Libyan M V Rim takes back ...
4,2010-06-02,international relations,The crew of the Libyan M V Rim takes back ...
...,...,...,...
9607,2025-10-06,disasters and accidents,Russo Ukrainian war Crimea attacks Ukraine...
9608,2025-10-06,international relations,Russo Ukrainian war Crimea attacks Ukraine...
9609,2025-10-06,law and crime and politics,Russo Ukrainian war Crimea attacks Ukraine...
9610,2025-10-06,politics and elections and economics,Russo Ukrainian war Crimea attacks Ukraine...
9611,2025-10-06,science and technology,Russo Ukrainian war Crimea attacks Ukraine...

In [24]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split']).text_cleaned.count())
a = a.reset_index()
a = a.rename({"text_cleaned": "count"}, axis=1)
a

     date_cleaned                           topic_split  count
0      2007-11-03           armed conflicts and attacks      1
1      2010-06-02           armed conflicts and attacks      9
2      2010-06-02                      arts and culture     18
3      2010-06-02               disasters and accidents      9
4      2010-06-02               international relations      9
...           ...                                   ...    ...
9607   2025-10-06               disasters and accidents      6
9608   2025-10-06               international relations      6
9609   2025-10-06            law and crime and politics      6
9610   2025-10-06  politics and elections and economics      6
9611   2025-10-06                science and technology      6

[9612 rows x 3 columns]

In [25]:
a.to_csv("news_data_ready_to_plot.csv", index=False)

In [8]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(df.date_cleaned, df.)

In [2]:
import joblib 
import pandas as pd
a = joblib.load("new_df.pkl")
b = pd.read_csv("cleaned_df.csv")

In [3]:
a

,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [6]:
b.groupby(['date', 'text_cleaned']).agg('topic_split'==str('topic_split'), ','.join)

TypeError: 'bool' object is not callable

In [10]:
c = pd.DataFrame(b.groupby(['date', 'text_cleaned'])['topic_split'].agg(','.join))
c = c.reset_index()
c

,date,text_cleaned,topic_split
0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...
1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [11]:
!pwd

/Users/thomasnguyen/news_project/data

In [12]:
c.to_csv("cleaned_df.csv")

In [14]:
len(b.topic_split.unique())

14

# improving the model

Maybe I can use a pretrained transformer model to classify the news articles

In [31]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as stats 
import numpy as np

In [32]:
cleaned_df = pd.read_csv("cleaned_df.csv")

In [33]:
cleaned_df

      Unnamed: 0.1  ...                                        topic_split
0                0  ...  armed conflicts and attacks,arts and culture,b...
1                1  ...  armed conflicts and attacks,disasters and acci...
2                2  ...  business and economics,disasters and accidents...
3                3  ...  armed conflicts and attacks,disasters and acci...
4                4  ...  armed conflicts and attacks,disasters and acci...
...            ...  ...                                                ...
1689          1689  ...  armed conflicts and attacks,arts and culture,b...
1690          1690  ...  armed conflicts and attacks,disasters and acci...
1691          1691  ...  armed conflicts and attacks,arts and culture,l...
1692          1692  ...  armed conflicts and attacks,business and econo...
1693          1693  ...  armed conflicts and attacks,disasters and acci...

[1694 rows x 5 columns]

In [34]:
X = cleaned_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'date', 'topic_split'],axis=1) 
y = cleaned_df.topic_split

In [36]:
X

                                           text_cleaned
0     War in Afghanistan  2001 2021    2021 Afghanis...
1     Russo Ukrainian War   2022 Russian invasion of...
2     In  India   a new  income tax  law comes into ...
3     Israel Hamas war   World Central Kitchen drone...
4     Middle Eastern crisis   Gaza war   Israeli inv...
...                                                 ...
1689  Afghanistan conflict   2021 evacuation from Af...
1690  Russo Ukrainian War   2022 Russian invasion of...
1691  Russian invasion of Ukraine   Zaporizhzhia Nuc...
1692  Russian invasion of Ukraine   Eastern Ukraine ...
1693  Middle Eastern crisis   Gaza war   2025 Gaza C...

[1694 rows x 1 columns]

In [35]:
X.text_cleaned.str.lower()

0       war in afghanistan  2001 2021    2021 afghanis...
1       russo ukrainian war   2022 russian invasion of...
2       in  india   a new  income tax  law comes into ...
3       israel hamas war   world central kitchen drone...
4       middle eastern crisis   gaza war   israeli inv...
                              ...
1689    afghanistan conflict   2021 evacuation from af...
1690    russo ukrainian war   2022 russian invasion of...
1691    russian invasion of ukraine   zaporizhzhia nuc...
1692    russian invasion of ukraine   eastern ukraine ...
1693    middle eastern crisis   gaza war   2025 gaza c...
Name: text_cleaned, Length: 1694, dtype: object

In [37]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

def get_minority_samples(X, y, ir_threshold=1.0):
    """Get samples belonging to minority labels (below mean IR)."""
    n_samples = y.shape[0]
    label_counts = y.sum(axis=0)
    mean_ir = np.mean(label_counts)
    
    minority_labels = np.where(label_counts < mean_ir)[0]
    minority_mask = y[:, minority_labels].sum(axis=1) > 0
    
    return X[minority_mask], y[minority_mask]

def mlsmote(X, y, n_samples=500, k_neighbors=5, random_state=42):
    """
    MLSMOTE: Synthetic Minority Oversampling for Multilabel data
    
    Parameters:
        X: np.ndarray — feature matrix (numeric)
        y: np.ndarray — binary label matrix (n_samples x n_labels)
        n_samples: int — number of synthetic samples to generate
        k_neighbors: int — number of nearest neighbors to use
    
    Returns:
        X_resampled, y_resampled (originals + synthetic)
    """
    rng = np.random.default_rng(random_state)
    
    # Focus on minority samples
    X_min, y_min = get_minority_samples(X, y)
    
    if len(X_min) < k_neighbors + 1:
        print(f"Warning: only {len(X_min)} minority samples, reducing k")
        k_neighbors = len(X_min) - 1
    
    # Fit KNN on minority samples
    knn = NearestNeighbors(n_neighbors=k_neighbors + 1)  # +1 because sample is own neighbor
    knn.fit(X_min)
    
    synthetic_X = []
    synthetic_y = []
    
    for _ in range(n_samples):
        # Pick a random minority sample as reference
        idx = rng.integers(0, len(X_min))
        x_ref = X_min[idx]
        y_ref = y_min[idx]
        
        # Find its k nearest neighbors
        _, neighbor_idxs = knn.kneighbors([x_ref])
        neighbor_idxs = neighbor_idxs[0][1:]  # exclude self
        
        # Pick a random neighbor
        nn_idx = rng.choice(neighbor_idxs)
        x_neighbor = X_min[nn_idx]
        y_neighbor = y_min[nn_idx]
        
        # Interpolate features
        gap = rng.random()
        x_synthetic = x_ref + gap * (x_neighbor - x_ref)
        
        # Union of labels (standard MLSMOTE label generation)
        y_synthetic = np.logical_or(y_ref, y_neighbor).astype(int)
        
        synthetic_X.append(x_synthetic)
        synthetic_y.append(y_synthetic)
    
    X_resampled = np.vstack([X, np.array(synthetic_X)])
    y_resampled = np.vstack([y, np.array(synthetic_y)])
    
    return X_resampled, y_resampled

In [39]:
mlb = MultiLabelBinarizer() 


y_lists = cleaned_df['topic_split'].apply(lambda x: [i.strip() for i in x.split(',')])

y_mlb = mlb.fit_transform(y_lists)

In [40]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'culture and entertainment',
       'disasters and accidents', 'entertainment',
       'health and environment', 'international relations',
       'law and crime and politics', 'other current events',
       'politics and elections and economics', 'religion and politics',
       'science and technology', 'sports'], dtype=object)

In [41]:
len(mlb.classes_)

14

In [42]:
y_mlb

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0]])

In [43]:
cleaned_df.topic_split

0       armed conflicts and attacks,arts and culture,b...
1       armed conflicts and attacks,disasters and acci...
2       business and economics,disasters and accidents...
3       armed conflicts and attacks,disasters and acci...
4       armed conflicts and attacks,disasters and acci...
                              ...
1689    armed conflicts and attacks,arts and culture,b...
1690    armed conflicts and attacks,disasters and acci...
1691    armed conflicts and attacks,arts and culture,l...
1692    armed conflicts and attacks,business and econo...
1693    armed conflicts and attacks,disasters and acci...
Name: topic_split, Length: 1694, dtype: object

In [44]:
y

0       armed conflicts and attacks,arts and culture,b...
1       armed conflicts and attacks,disasters and acci...
2       business and economics,disasters and accidents...
3       armed conflicts and attacks,disasters and acci...
4       armed conflicts and attacks,disasters and acci...
                              ...
1689    armed conflicts and attacks,arts and culture,b...
1690    armed conflicts and attacks,disasters and acci...
1691    armed conflicts and attacks,arts and culture,l...
1692    armed conflicts and attacks,business and econo...
1693    armed conflicts and attacks,disasters and acci...
Name: topic_split, Length: 1694, dtype: object

In [45]:
y_mlb

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0]])

In [46]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'culture and entertainment',
       'disasters and accidents', 'entertainment',
       'health and environment', 'international relations',
       'law and crime and politics', 'other current events',
       'politics and elections and economics', 'religion and politics',
       'science and technology', 'sports'], dtype=object)

In [47]:
y_mlb

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0]])

In [48]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [49]:
# getting the stop words

stop_words = list(set(stopwords.words('english')))

In [50]:
X

                                           text_cleaned
0     War in Afghanistan  2001 2021    2021 Afghanis...
1     Russo Ukrainian War   2022 Russian invasion of...
2     In  India   a new  income tax  law comes into ...
3     Israel Hamas war   World Central Kitchen drone...
4     Middle Eastern crisis   Gaza war   Israeli inv...
...                                                 ...
1689  Afghanistan conflict   2021 evacuation from Af...
1690  Russo Ukrainian War   2022 Russian invasion of...
1691  Russian invasion of Ukraine   Zaporizhzhia Nuc...
1692  Russian invasion of Ukraine   Eastern Ukraine ...
1693  Middle Eastern crisis   Gaza war   2025 Gaza C...

[1694 rows x 1 columns]

In [51]:
vectorizer = TfidfVectorizer(max_features=500, stop_words=stop_words)
X = vectorizer.fit_transform(X['text_cleaned'].str.lower()).toarray()  # must be dense
y = y_mlb
# --- Stratified split BEFORE resampling ---
splitter = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in splitter.split(X, y):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

# --- Check label distribution improved ---
before = y_train.sum(axis=0)
after = y_train_res.sum(axis=0)
comparison = pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_)
print(comparison)

Before: 1350 samples
After:  1650 samples
                                      before  after
armed conflicts and attacks             1282   1581
arts and culture                         282    425
business and economics                   545    788
culture and entertainment                  1      1
disasters and accidents                 1101   1384
entertainment                              2      3
health and environment                   654    840
international relations                  837   1085
law and crime and politics              1124   1415
other current events                      12     14
politics and elections and economics     971   1246
religion and politics                      5      6
science and technology                   380    547
sports                                   486    717

In [52]:
X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

# --- Check label distribution improved ---
before = y_train.sum(axis=0)
after = y_train_res.sum(axis=0)
comparison = pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_)
print(comparison)

Before: 1350 samples
After:  1650 samples
                                      before  after
armed conflicts and attacks             1282   1581
arts and culture                         282    425
business and economics                   545    788
culture and entertainment                  1      1
disasters and accidents                 1101   1384
entertainment                              2      3
health and environment                   654    840
international relations                  837   1085
law and crime and politics              1124   1415
other current events                      12     14
politics and elections and economics     971   1246
religion and politics                      5      6
science and technology                   380    547
sports                                   486    717

In [68]:
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

In [69]:
model = XGBClassifier()

model.fit(X_train_res, y_train_res)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [70]:
pred = model.predict(X_test)

# metrics

In [71]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_curve

In [72]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()

In [73]:
MR

0.13662790697674418

In [74]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [75]:
loss01

0.8633720930232558

In [76]:
accuracy_score(pred, y_test)

0.13662790697674418

In [77]:
f1_score(y_test, pred, average='micro')

0.8350676378772113

In [78]:
from sklearn.metrics import f1_score
f1_score(y_test, pred, average='macro')

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

0.5608670304010591

In [79]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

0.8204270959717821

In [80]:
from sklearn.model_selection import cross_val_score

In [81]:
cross_val_score(model, X, y, scoring='f1_macro', cv=5)

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

array([0.50810595, 0.52067843, 0.52705469, 0.52085957, 0.49854761])

In [144]:
# tuning the model

In [82]:
from sklearn.model_selection import GridSearchCV

In [83]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [20, 30, 40],
    'eta': [0.1, 0.3],

}


# Run grid search
grid_search = GridSearchCV(
    estimator=XGBClassifier(),
    param_grid=param_grid,
    scoring='f1_macro',       # use macro F1 for imbalanced multilabel
    cv=4,
    n_jobs=-1,                # use all CPU cores
    verbose=2
)

grid_search.fit(X_train_res, y_train_res)

Fitting 4 folds for each of 18 candidates, totalling 72 fits
[CV] END .............eta=0.1, max_depth=20, n_estimators=50; total time= 1.6min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=20, n_estimators=50; total time= 1.7min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=20, n_estimators=50; total time= 1.7min
[CV] END .............eta=0.1, max_depth=20, n_estimators=50; total time= 1.7min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=100; total time= 1.9min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=100; total time= 2.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=100; total time= 2.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=100; total time= 2.1min
[CV] END .............eta=0.1, max_depth=30, n_estimators=50; total time= 1.6min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=30, n_estimators=50; total time= 1.4min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=30, n_estimators=50; total time= 1.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=30, n_estimators=50; total time= 1.6min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=200; total time= 2.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=200; total time= 2.3min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=200; total time= 2.4min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=20, n_estimators=200; total time= 2.4min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=100; total time= 1.9min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=100; total time= 1.9min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=100; total time= 1.8min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=100; total time= 2.0min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=200; total time= 2.2min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=30, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=40, n_estimators=50; total time= 1.4min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=40, n_estimators=50; total time= 1.2min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.1, max_depth=40, n_estimators=50; total time= 1.4min
[CV] END .............eta=0.1, max_depth=40, n_estimators=50; total time= 1.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=100; total time= 2.2min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=100; total time= 2.2min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=100; total time= 2.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=100; total time= 2.3min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=20, n_estimators=50; total time=  35.3s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=20, n_estimators=50; total time=  34.0s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=20, n_estimators=50; total time=  29.3s
[CV] END .............eta=0.3, max_depth=20, n_estimators=50; total time=  34.1s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=200; total time= 2.2min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.1, max_depth=40, n_estimators=200; total time= 2.5min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=100; total time=  45.1s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=100; total time=  49.6s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=100; total time=  52.1s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=100; total time=  53.9s
[CV] END ............eta=0.3, max_depth=20, n_estimators=200; total time=  52.0s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=200; total time= 1.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=200; total time= 1.0min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=20, n_estimators=200; total time= 1.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=30, n_estimators=50; total time=  30.5s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=30, n_estimators=50; total time=  29.7s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=30, n_estimators=50; total time=  27.0s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=30, n_estimators=50; total time=  31.5s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=100; total time=  48.2s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=100; total time=  47.3s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=100; total time=  47.5s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=100; total time=  53.9s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=200; total time=  55.2s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=200; total time= 1.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=200; total time= 1.1min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=40, n_estimators=50; total time=  29.3s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=40, n_estimators=50; total time=  29.2s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=30, n_estimators=200; total time= 1.1min
[CV] END .............eta=0.3, max_depth=40, n_estimators=50; total time=  30.7s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END .............eta=0.3, max_depth=40, n_estimators=50; total time=  27.1s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=100; total time=  53.2s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=100; total time=  50.7s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=100; total time=  54.6s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=100; total time=  55.5s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=200; total time=  48.0s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=200; total time= 1.0min

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=200; total time=  59.6s

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

[CV] END ............eta=0.3, max_depth=40, n_estimators=200; total time=  55.1s

GridSearchCV(cv=4,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=Non...
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'eta': [0.1, 0.3], 'max_depth': [20, 30, 40],
                         'n_estimators': [50, 100, 200]},
             scoring='f1_macro', verbose=2)

In [84]:
pred = grid_search.predict(X_test)

In [85]:
accuracy_score(y_test, pred)

0.14534883720930233

In [86]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

0.8188909821628695

In [87]:
f1_score(y_pred=pred, y_true=y_test, average='macro')

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

0.5593103266913494

In [89]:
f1_score(y_pred=pred, y_true=y_test, average='micro')

0.835548605681522

In [46]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()
MR

0.10324483775811209

In [90]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [91]:
loss01

0.8546511627906976

In [92]:
import joblib 
joblib.dump(grid_search, 'news_topic_classifier.pkl')

['news_topic_classifier.pkl']

In [94]:
joblib.dump(mlb, "mlb.pkl")

['mlb.pkl']

In [95]:
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

In [96]:
text="""An urgent public health alert has been issued after a deadly meningitis outbreak in Kent, with health workers across England urged to look out for signs of infection.
The UK Health Security Agency (UKHSA) issued the alert as a vaccination programme targeting about 5,000 students began at the University of Kent, following an outbreak thought to have originated at a nightclub in Canterbury.
A 21-year-old university student and Juliette, a sixth former at Queen Elizabeth's Grammar School in Faversham, have died, with the number of confirmed and suspected cases now at 20.
The UKHSA alert is unusual but has been used in recent years for MPox and other public health issues.
UKHSA chief executive Susan Hopkins told the BBC that it was trying to work out why the infection had spread so fast in Canterbury.
She said vaccines held by the government would be used for NHS patients, including students in Kent, but it would not rule out supplying some to pharmacies.
A case has also now been confirmed at Canterbury Christ Church University.
Christ Church student Tyra Skinner, 20, contracted meningitis after attending the Club Chemistry nightclub, her parents said."""

In [97]:
text_tfidf = vectorizer.transform([text])

In [99]:
prediction = model.predict(text_tfidf)

In [100]:
pd.DataFrame(prediction, columns=mlb.classes_)

   armed conflicts and attacks  ...  sports
0                          1.0  ...     1.0

[1 rows x 14 columns]

In [90]:
joblib.dump(vectorizer, "tfidf_vectoriser.pkl")

['tfidf_vectoriser.pkl']

In [91]:
pred

array([[1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 0],
       ...,
       [1, 1, 1, ..., 0, 1, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 1, 0]])

In [92]:
np.shape(pred)

(339, 24)

In [4]:
# assessing the dataset

import pandas as pd

In [5]:
!pwd

/Users/thomasnguyen/news_project/data

In [6]:
cleaned_df = pd.read_csv("cleaned_df.csv")

In [7]:
cleaned_df

      Unnamed: 0  ...                                        topic_split
0              0  ...  armed conflicts and attacks,arts and culture,b...
1              1  ...  armed conflicts and attacks,disasters and acci...
2              2  ...  business and economics,disasters and accidents...
3              3  ...  armed conflicts and attacks,disasters and acci...
4              4  ...  armed conflicts and attacks,disasters and acci...
...          ...  ...                                                ...
1689        1689  ...  armed conflicts and attacks,arts and culture,b...
1690        1690  ...  armed conflicts and attacks,disasters and acci...
1691        1691  ...  armed conflicts and attacks,arts and culture,l...
1692        1692  ...  armed conflicts and attacks,business and econo...
1693        1693  ...  armed conflicts and attacks,disasters and acci...

[1694 rows x 4 columns]

In [8]:
extracted_topics = pd.read_csv("extracted_topics.csv")

In [9]:
extracted_topics

     Unnamed: 0  year  month                        topic  count year_month
0             0  2007     11  Armed conflicts and attacks      1    2007-11
1             1  2010      6    culture and entertainment      6    2010-06
2             2  2010      6  Armed conflicts and attacks      8    2010-06
3             3  2010      6                          Art      6    2010-06
4             4  2010      6         Business and economy      3    2010-06
..          ...   ...    ...                          ...    ...        ...
701         701  2025     10      International relations      4    2025-10
702         702  2025     10                Law and crime      5    2025-10
703         703  2025     10       Politics and elections      6    2025-10
704         704  2025     10       Science and technology      3    2025-10
705         705  2025     10                       Sports      3    2025-10

[706 rows x 6 columns]

In [10]:
extracted_topics.topic.value_counts()

topic
Armed conflicts and attacks    68
Law and crime                  68
Business and economy           64
Disasters and accidents        64
Politics and elections         64
                               ..
Law & crime                     1
Law and politics                1
Other current events            1
Politics & elections            1
Disaster and accidents          1
Name: count, Length: 63, dtype: int64

In [16]:
test = standardize_topics(extracted_topics)

In [17]:
test

     Unnamed: 0  year  month                        topic  count year_month
0             0  2007     11  armed conflicts and attacks      1    2007-11
1             1  2010      6    culture and entertainment      6    2010-06
2             2  2010      6  armed conflicts and attacks      8    2010-06
3             3  2010      6             arts and culture      6    2010-06
4             4  2010      6       business and economics      3    2010-06
..          ...   ...    ...                          ...    ...        ...
701         701  2025     10      international relations      4    2025-10
702         702  2025     10                law and crime      5    2025-10
703         703  2025     10       politics and elections      6    2025-10
704         704  2025     10       science and technology      3    2025-10
705         705  2025     10                       sports      3    2025-10

[706 rows x 6 columns]

In [25]:
sorted(test.topic.unique())

['armed conflicts and attacks',
 'arts and culture',
 'business and economics',
 'culture & entertainment',
 'culture and entertainment',
 'culture and society',
 'disasters and accidents',
 'environment',
 'health',
 'international relations',
 'law and crime',
 'other',
 'politics and elections',
 'religion',
 'science and technology',
 'sports']

In [22]:
a

In [26]:

def standardize_topic_split(df: pd.DataFrame, col: str = "topic_split") -> pd.DataFrame:
    """
    Splits each comma-separated topic string, maps every individual
    topic to its canonical label, deduplicates, and rejoins.
    """
    df = df.copy()

    def clean_row(value: str) -> str:
        topics = [t.strip() for t in value.split(",")]
        mapped = [TOPIC_MAP.get(t, t.lower().strip()) for t in topics]
        deduped = list(dict.fromkeys(mapped))          # preserve order, remove dupes
        return ",".join(deduped)

    df[col] = df[col].astype(str).apply(clean_row)
    return df


# Apply it
clean_df = standardize_topic_split(cleaned_df, col="topic_split")

# Verify
all_topics = (
    clean_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .unique()
)
print(sorted(all_topics))

['armed conflicts and attacks', 'arts and culture', 'business and economics', 'culture and entertainment', 'disasters and accidents', 'entertainment', 'health and environment', 'international relations', 'law and crime and politics', 'other current events', 'politics and elections and economics', 'religion and politics', 'science and technology', 'sports']