In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_df.csv")

In [7]:
df

,Unnamed: 0,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
0,1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
1,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
3,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
4,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...,...
58583,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
58584,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
58585,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
58586,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
58587,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [16]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split'])['text_cleaned'].sum())

a = a.reset_index()
a

,date_cleaned,topic_split,text_cleaned
0,2007-11-03,armed conflicts and attacks,2007 Pakistani state of emergency President ...
1,2010-06-02,armed conflicts and attacks,The crew of the Libyan M V Rim takes back ...
2,2010-06-02,arts and culture,The crew of the Libyan M V Rim takes back ...
3,2010-06-02,disasters and accidents,The crew of the Libyan M V Rim takes back ...
4,2010-06-02,international relations,The crew of the Libyan M V Rim takes back ...
...,...,...,...
9607,2025-10-06,disasters and accidents,Russo Ukrainian war Crimea attacks Ukraine...
9608,2025-10-06,international relations,Russo Ukrainian war Crimea attacks Ukraine...
9609,2025-10-06,law and crime and politics,Russo Ukrainian war Crimea attacks Ukraine...
9610,2025-10-06,politics and elections and economics,Russo Ukrainian war Crimea attacks Ukraine...
9611,2025-10-06,science and technology,Russo Ukrainian war Crimea attacks Ukraine...

In [24]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split']).text_cleaned.count())
a = a.reset_index()
a = a.rename({"text_cleaned": "count"}, axis=1)
a

     date_cleaned                           topic_split  count
0      2007-11-03           armed conflicts and attacks      1
1      2010-06-02           armed conflicts and attacks      9
2      2010-06-02                      arts and culture     18
3      2010-06-02               disasters and accidents      9
4      2010-06-02               international relations      9
...           ...                                   ...    ...
9607   2025-10-06               disasters and accidents      6
9608   2025-10-06               international relations      6
9609   2025-10-06            law and crime and politics      6
9610   2025-10-06  politics and elections and economics      6
9611   2025-10-06                science and technology      6

[9612 rows x 3 columns]

In [25]:
a.to_csv("news_data_ready_to_plot.csv", index=False)

In [8]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(df.date_cleaned, df.)

In [2]:
import joblib 
import pandas as pd
a = joblib.load("new_df.pkl")
b = pd.read_csv("cleaned_df.csv")

In [3]:
a

,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [6]:
b.groupby(['date', 'text_cleaned']).agg('topic_split'==str('topic_split'), ','.join)

TypeError: 'bool' object is not callable

In [10]:
c = pd.DataFrame(b.groupby(['date', 'text_cleaned'])['topic_split'].agg(','.join))
c = c.reset_index()
c

,date,text_cleaned,topic_split
0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...
1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [11]:
!pwd

/Users/thomasnguyen/news_project/data

In [12]:
c.to_csv("cleaned_df.csv")

In [14]:
len(b.topic_split.unique())

14

# improving the model

Maybe I can use a pretrained transformer model to classify the news articles

In [105]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as stats 
import numpy as np 
import re

In [134]:
cleaned_df = pd.read_csv("cleaned_df.csv")

In [135]:
cleaned_df = pd.read_csv("cleaned_df.csv")
topic_counts = (
    cleaned_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

print(topic_counts)

topic_split
armed conflicts and attacks             1604
law and crime and politics              1405
disasters and accidents                 1384
politics and elections and economics    1214
international relations                 1046
health and environment                   817
business and economics                   681
sports                                   608
science and technology                   475
arts and culture                         353
other current events                      15
religion and politics                      6
entertainment                              3
culture and entertainment                  1
Name: count, dtype: int64

In [136]:
cleaned_df.head()

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."

In [137]:
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture and entertainment", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture and society", "other") 
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace(",environment,", ",other,") 
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("religion", 'other')
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture & entertainment", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("other current events", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("other and politics", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace(",entertainment", ",other")

#cleaned_df.topic_split = cleaned_df.topic_split.str.replace("", ",other,")

In [138]:
cleaned_df = cleaned_df[~cleaned_df.topic_split.str.contains("other", na=False)]
cleaned_df

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...,...,...
1689,1689,1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,1690,1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,1691,1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,1692,1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,1693,1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [139]:

topic_counts = (
    cleaned_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

print(topic_counts)

topic_split
armed conflicts and attacks             1587
law and crime and politics              1389
disasters and accidents                 1374
politics and elections and economics    1198
international relations                 1035
health and environment                   813
business and economics                   671
sports                                   596
science and technology                   462
arts and culture                         344
Name: count, dtype: int64

In [140]:
cleaned_df

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...,...,...
1689,1689,1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,1690,1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,1691,1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,1692,1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,1693,1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [141]:
X = cleaned_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'date', 'topic_split'],axis=1) 
X.text_cleaned=X.text_cleaned.str.replace("[^a-zA-Z0-9]+", " ", regex=True).str.strip().str.lower() 
y = cleaned_df.topic_split

In [142]:
X

                                           text_cleaned
0     war in afghanistan 2001 2021 2021 afghanistan ...
1     russo ukrainian war 2022 russian invasion of u...
2     in india a new income tax law comes into effec...
3     israel hamas war world central kitchen drone s...
4     middle eastern crisis gaza war israeli invasio...
...                                                 ...
1689  afghanistan conflict 2021 evacuation from afgh...
1690  russo ukrainian war 2022 russian invasion of u...
1691  russian invasion of ukraine zaporizhzhia nucle...
1692  russian invasion of ukraine eastern ukraine ca...
1693  middle eastern crisis gaza war 2025 gaza city ...

[1669 rows x 1 columns]

In [143]:
X.text_cleaned.str.lower()

0       war in afghanistan 2001 2021 2021 afghanistan ...
1       russo ukrainian war 2022 russian invasion of u...
2       in india a new income tax law comes into effec...
3       israel hamas war world central kitchen drone s...
4       middle eastern crisis gaza war israeli invasio...
                              ...
1689    afghanistan conflict 2021 evacuation from afgh...
1690    russo ukrainian war 2022 russian invasion of u...
1691    russian invasion of ukraine zaporizhzhia nucle...
1692    russian invasion of ukraine eastern ukraine ca...
1693    middle eastern crisis gaza war 2025 gaza city ...
Name: text_cleaned, Length: 1669, dtype: object

In [144]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

def get_minority_samples(X, y, ir_threshold=1.0):
    """Get samples belonging to minority labels (below mean IR)."""
    n_samples = y.shape[0]
    label_counts = y.sum(axis=0)
    mean_ir = np.mean(label_counts)
    
    minority_labels = np.where(label_counts < mean_ir)[0]
    minority_mask = y[:, minority_labels].sum(axis=1) > 0
    
    return X[minority_mask], y[minority_mask]

def mlsmote(X, y, n_samples=500, k_neighbors=5, random_state=42):
    """
    MLSMOTE: Synthetic Minority Oversampling for Multilabel data
    
    Parameters:
        X: np.ndarray — feature matrix (numeric)
        y: np.ndarray — binary label matrix (n_samples x n_labels)
        n_samples: int — number of synthetic samples to generate
        k_neighbors: int — number of nearest neighbors to use
    
    Returns:
        X_resampled, y_resampled (originals + synthetic)
    """
    rng = np.random.default_rng(random_state)
    
    # Focus on minority samples
    X_min, y_min = get_minority_samples(X, y)
    
    if len(X_min) < k_neighbors + 1:
        print(f"Warning: only {len(X_min)} minority samples, reducing k")
        k_neighbors = len(X_min) - 1
    
    # Fit KNN on minority samples
    knn = NearestNeighbors(n_neighbors=k_neighbors + 1)  # +1 because sample is own neighbor
    knn.fit(X_min)
    
    synthetic_X = []
    synthetic_y = []
    
    for _ in range(n_samples):
        # Pick a random minority sample as reference
        idx = rng.integers(0, len(X_min))
        x_ref = X_min[idx]
        y_ref = y_min[idx]
        
        # Find its k nearest neighbors
        _, neighbor_idxs = knn.kneighbors([x_ref])
        neighbor_idxs = neighbor_idxs[0][1:]  # exclude self
        
        # Pick a random neighbor
        nn_idx = rng.choice(neighbor_idxs)
        x_neighbor = X_min[nn_idx]
        y_neighbor = y_min[nn_idx]
        
        # Interpolate features
        gap = rng.random()
        x_synthetic = x_ref + gap * (x_neighbor - x_ref)
        
        # Union of labels (standard MLSMOTE label generation)
        y_synthetic = np.logical_or(y_ref, y_neighbor).astype(int)
        
        synthetic_X.append(x_synthetic)
        synthetic_y.append(y_synthetic)
    
    X_resampled = np.vstack([X, np.array(synthetic_X)])
    y_resampled = np.vstack([y, np.array(synthetic_y)])
    
    return X_resampled, y_resampled

In [145]:
mlb = MultiLabelBinarizer() 


y_lists = cleaned_df['topic_split'].apply(lambda x: [i.strip() for i in x.split(',')])

y_mlb = mlb.fit_transform(y_lists)

In [146]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'disasters and accidents',
       'health and environment', 'international relations',
       'law and crime and politics',
       'politics and elections and economics', 'science and technology',
       'sports'], dtype=object)

In [147]:
len(mlb.classes_)

10

In [148]:
y_mlb

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0]])

In [149]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'disasters and accidents',
       'health and environment', 'international relations',
       'law and crime and politics',
       'politics and elections and economics', 'science and technology',
       'sports'], dtype=object)

In [150]:
y_mlb

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0]])

In [151]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [152]:
# getting the stop words

stop_words = list(set(stopwords.words('english')))

In [153]:
vectorizer = TfidfVectorizer(max_features=10000, stop_words=stop_words, lowercase=True, ngram_range=(1,10), min_df=10)
X = vectorizer.fit_transform(X['text_cleaned'].str.lower()).toarray()  # must be dense
y = y_mlb
# --- Stratified split BEFORE resampling ---
splitter = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in splitter.split(X, y):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

# --- Check label distribution improved ---
before = y_train.sum(axis=0)
after = y_train_res.sum(axis=0)
comparison = pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_)
print(comparison)

Before: 1327 samples
After:  1627 samples
                                      before  after
armed conflicts and attacks             1263   1562
arts and culture                         275    407
business and economics                   537    748
disasters and accidents                 1095   1380
health and environment                   650    860
international relations                  828   1081
law and crime and politics              1111   1400
politics and elections and economics     958   1236
science and technology                   370    512
sports                                   477    653

In [154]:
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
# trying a one vs rest

from sklearn.multiclass import OneVsRestClassifier

In [155]:
model = OneVsRestClassifier(XGBClassifier())

model.fit(X_train_res, y_train_res)

OneVsRestClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None,
                                            feature_weights=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=None, n_jobs=None,
                                            num_parallel_tree=None, ...))

In [156]:
pred = model.predict(X_test)

# metrics

In [157]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_curve

In [158]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()

In [159]:
MR

0.195906432748538

In [160]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [161]:
loss01

0.804093567251462

In [162]:
accuracy_score(pred, y_test)

0.195906432748538

In [163]:
f1_score(y_test, pred, average='micro')

0.8611627289620387

In [164]:
from sklearn.metrics import f1_score
f1_score(y_test, pred, average='macro')

0.7887857205001858

In [165]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

0.8509779654940333

In [166]:
from sklearn.model_selection import cross_val_score

In [167]:
# tuning the model

In [168]:
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

In [169]:


opt = BayesSearchCV(
    OneVsRestClassifier(XGBClassifier()),

                        
                        
    {
        'estimator__n_estimators': Integer(100, 500, prior='log-uniform'),
        'estimator__max_depth': Integer(10, 70, prior='log-uniform'),
        'estimator__eta': Real(0.1, 0.3),
        
    },
    n_iter=32,
    random_state=0
)

_ = opt.fit(X_train_res, y_train_res)

KeyboardInterrupt:

In [319]:
# metrics for bayes search

pred = opt.predict(X_test)
print (f"accuracy: {accuracy_score(y_true=y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=y_test, average='macro')}")

accuracy: 0.1457725947521866
f1 score weighted: 0.8201170121183478
f1 score micro: 0.839622641509434
f1 score macro: 0.6654519083283263

In [ ]:
param_grid = {
    'estimator__n_estimators': [200, 300],
    'estimator__max_depth': [50, 60],
    'estimator__eta': [0.1, 0.3],

}

# Run grid search
grid_search = GridSearchCV(
    estimator=OneVsRestClassifier(XGBClassifier()),
    param_grid=param_grid,
    scoring='f1_macro',       # use macro F1 for imbalanced multilabel
    cv=5,
    n_jobs=-1,                # use all CPU cores
    verbose=2
)

grid_search.fit(X_train_res, y_train_res)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=50; total time= 9.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=50; total time=10.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=50; total time=10.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=50; total time=11.0min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=50; total time=11.0min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=100; total time=15.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=100; total time=15.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=100; total time=16.0min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=100; total time=13.9min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=100; total time=15.3min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=200; total time=20.9min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=200; total time=20.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=200; total time=20.9min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=200; total time=18.7min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=200; total time=20.7min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=300; total time=24.5min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=50; total time=10.2min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=50; total time=10.5min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=50; total time=10.9min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=300; total time=25.3min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=300; total time=25.5min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=50; total time=10.8min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=50; total time= 9.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=300; total time=23.8min
[CV] END estimator__eta=0.1, estimator__max_depth=50, estimator__n_estimators=300; total time=26.1min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=100; total time=15.6min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=100; total time=15.6min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=100; total time=14.4min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=100; total time=15.8min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=100; total time=15.8min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=200; total time=21.5min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=200; total time=21.1min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=200; total time=21.4min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=200; total time=21.3min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=200; total time=19.4min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=50; total time= 6.1min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=50; total time= 6.0min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=50; total time= 6.2min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=300; total time=24.7min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=300; total time=24.7min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=300; total time=24.5min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=50; total time= 6.0min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=50; total time= 5.5min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=100; total time= 7.9min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=300; total time=24.1min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=100; total time= 7.2min
[CV] END estimator__eta=0.1, estimator__max_depth=60, estimator__n_estimators=300; total time=22.1min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=100; total time= 7.8min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=200; total time=10.0min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=200; total time= 9.4min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=200; total time= 9.5min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=200; total time= 8.9min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=200; total time= 9.3min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=300; total time=12.7min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=300; total time=12.6min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=300; total time=12.6min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=50; total time= 5.6min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=50; total time= 5.6min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=50; total time= 5.8min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=300; total time=13.0min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=50; total time= 5.5min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=50; total time= 5.9min
[CV] END estimator__eta=0.3, estimator__max_depth=50, estimator__n_estimators=300; total time=12.6min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=100; total time= 7.7min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=100; total time= 6.6min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=200; total time=10.2min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=200; total time=10.0min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=200; total time= 9.4min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=200; total time= 9.5min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=200; total time= 8.7min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=300; total time=10.2min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=300; total time=10.0min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=300; total time= 9.1min

Exception ignored in: <function ResourceTracker.__del__ at 0x1051a5940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x107345940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=300; total time= 6.8min
[CV] END estimator__eta=0.3, estimator__max_depth=60, estimator__n_estimators=300; total time= 7.0min

Exception ignored in: <function ResourceTracker.__del__ at 0x10545d940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1073ad940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x105cf9940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x103abd940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

GridSearchCV(cv=5,
             estimator=OneVsRestClassifier(estimator=XGBClassifier(base_score=None,
                                                                   booster=None,
                                                                   callbacks=None,
                                                                   colsample_bylevel=None,
                                                                   colsample_bynode=None,
                                                                   colsample_bytree=None,
                                                                   device=None,
                                                                   early_stopping_rounds=None,
                                                                   enable_categorical=False,
                                                                   eval_metric=None,
                                                                   feature_types=None,
                                                                   feature_weights=None,
                                                                   gamma=None,
                                                                   grow_policy=None,
                                                                   importance_type=No...
                                                                   max_cat_to_onehot=None,
                                                                   max_delta_step=None,
                                                                   max_depth=None,
                                                                   max_leaves=None,
                                                                   min_child_weight=None,
                                                                   missing=nan,
                                                                   monotone_constraints=None,
                                                                   multi_strategy=None,
                                                                   n_estimators=None,
                                                                   n_jobs=None,
                                                                   num_parallel_tree=None, ...)),
             n_jobs=-1,
             param_grid={'estimator__eta': [0.1, 0.3],
                         'estimator__max_depth': [50, 60],
                         'estimator__n_estimators': [50, 100, 200, 300]},
             scoring='f1_macro', verbose=2)

Exception ignored in: <function ResourceTracker.__del__ at 0x10a665940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x1035f5940>
Traceback (most recent call last):
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/opt/miniconda3/envs/news_project/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

In [183]:
grid_search

GridSearchCV(cv=5,
             estimator=OneVsRestClassifier(estimator=XGBClassifier(base_score=None,
                                                                   booster=None,
                                                                   callbacks=None,
                                                                   colsample_bylevel=None,
                                                                   colsample_bynode=None,
                                                                   colsample_bytree=None,
                                                                   device=None,
                                                                   early_stopping_rounds=None,
                                                                   enable_categorical=False,
                                                                   eval_metric=None,
                                                                   feature_types=None,
                                                                   feature_weights=None,
                                                                   gamma=None,
                                                                   grow_policy=None,
                                                                   importance_type=No...
                                                                   max_cat_to_onehot=None,
                                                                   max_delta_step=None,
                                                                   max_depth=None,
                                                                   max_leaves=None,
                                                                   min_child_weight=None,
                                                                   missing=nan,
                                                                   monotone_constraints=None,
                                                                   multi_strategy=None,
                                                                   n_estimators=None,
                                                                   n_jobs=None,
                                                                   num_parallel_tree=None, ...)),
             n_jobs=-1,
             param_grid={'estimator__eta': [0.1, 0.3],
                         'estimator__max_depth': [50, 60],
                         'estimator__n_estimators': [50, 100, 200, 300]},
             scoring='f1_macro', verbose=2)

In [172]:
from sklearn.metrics import hamming_loss, label_ranking_loss

In [184]:
pred = grid_search.predict(X_test)
print (f"accuracy: {accuracy_score(y_true=y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=y_test, average='macro')}")
print (f"hamming loss: {hamming_loss(y_true=y_test, y_pred=pred)}")

accuracy: 0.21637426900584794
f1 score weighted: 0.8500283051755944
f1 score micro: 0.8625567120362957
f1 score macro: 0.7838257222069362
hamming loss: 0.15058479532163743

In [175]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()
MR

0.21637426900584794

In [176]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [177]:
loss01

0.783625730994152

In [ ]:
import joblib 
joblib.dump(grid_search, '../models/news_topic_classifier/news_topic_classifier.pkl')

['../models/news_topic_classifier.pkl']

In [ ]:
joblib.dump(mlb, "../models/news_topic_classifier/mlb.pkl")

['../models/mlb.pkl']

In [ ]:
joblib.dump(vectorizer, '../models/news_topic_classifier/tfidf_vectorizer.pkl')

['../models/tfidf_vectorizer.pkl']

# trying a neural network

In [14]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
import joblib