In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("cleaned_df.csv")

In [7]:
df

,Unnamed: 0,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
0,1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
1,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
3,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
4,2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...,...
58583,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
58584,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
58585,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
58586,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
58587,7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [16]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split'])['text_cleaned'].sum())

a = a.reset_index()
a

,date_cleaned,topic_split,text_cleaned
0,2007-11-03,armed conflicts and attacks,2007 Pakistani state of emergency President ...
1,2010-06-02,armed conflicts and attacks,The crew of the Libyan M V Rim takes back ...
2,2010-06-02,arts and culture,The crew of the Libyan M V Rim takes back ...
3,2010-06-02,disasters and accidents,The crew of the Libyan M V Rim takes back ...
4,2010-06-02,international relations,The crew of the Libyan M V Rim takes back ...
...,...,...,...
9607,2025-10-06,disasters and accidents,Russo Ukrainian war Crimea attacks Ukraine...
9608,2025-10-06,international relations,Russo Ukrainian war Crimea attacks Ukraine...
9609,2025-10-06,law and crime and politics,Russo Ukrainian war Crimea attacks Ukraine...
9610,2025-10-06,politics and elections and economics,Russo Ukrainian war Crimea attacks Ukraine...
9611,2025-10-06,science and technology,Russo Ukrainian war Crimea attacks Ukraine...

In [24]:
a = pd.DataFrame(df.groupby(['date_cleaned', 'topic_split']).text_cleaned.count())
a = a.reset_index()
a = a.rename({"text_cleaned": "count"}, axis=1)
a

     date_cleaned                           topic_split  count
0      2007-11-03           armed conflicts and attacks      1
1      2010-06-02           armed conflicts and attacks      9
2      2010-06-02                      arts and culture     18
3      2010-06-02               disasters and accidents      9
4      2010-06-02               international relations      9
...           ...                                   ...    ...
9607   2025-10-06               disasters and accidents      6
9608   2025-10-06               international relations      6
9609   2025-10-06            law and crime and politics      6
9610   2025-10-06  politics and elections and economics      6
9611   2025-10-06                science and technology      6

[9612 rows x 3 columns]

In [25]:
a.to_csv("news_data_ready_to_plot.csv", index=False)

In [8]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(df.date_cleaned, df.)

In [2]:
import joblib 
import pandas as pd
a = joblib.load("new_df.pkl")
b = pd.read_csv("cleaned_df.csv")

In [3]:
a

,topic,date,text,text_cleaned,date_cleaned,topic_cleaned,topic_split
1123,Armed conflicts and attacks,"November 3, 2007","2007 Pakistani state of emergency,\n,President...",2007 Pakistani state of emergency President ...,2007-11-03,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,armed conflicts and attacks
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,arts and culture
2097,"Armed conflicts and attacks,Arts and culture, ...","June 2, 2010","The crew of the ,Libyan, M/V ,Rim, takes back ...",The crew of the Libyan M V Rim takes back ...,2010-06-02,Armed conflicts and attacks,disasters and accidents
...,...,...,...,...,...,...,...
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,health and environment
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,international relations
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,law and crime and politics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,politics and elections and economics
7309,"Attacks and armed conflicts,Business and econo...","February 28, 2025","2025 Darul Uloom Haqqania bombing,\n,Five peop...",2025 Darul Uloom Haqqania bombing Five peopl...,2025-02-28,Science and technology,science and technology

In [6]:
b.groupby(['date', 'text_cleaned']).agg('topic_split'==str('topic_split'), ','.join)

TypeError: 'bool' object is not callable

In [10]:
c = pd.DataFrame(b.groupby(['date', 'text_cleaned'])['topic_split'].agg(','.join))
c = c.reset_index()
c

,date,text_cleaned,topic_split
0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...
1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [11]:
!pwd

/Users/thomasnguyen/news_project/data

In [12]:
c.to_csv("cleaned_df.csv")

In [14]:
len(b.topic_split.unique())

14

# improving the model

Maybe I can use a pretrained transformer model to classify the news articles

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import scipy.stats as stats 
import numpy as np 
import re

In [17]:
cleaned_df = pd.read_csv("cleaned_df.csv")

In [18]:
cleaned_df = pd.read_csv("cleaned_df.csv")
topic_counts = (
    cleaned_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

print(topic_counts)

topic_split
armed conflicts and attacks             1604
law and crime and politics              1405
disasters and accidents                 1384
politics and elections and economics    1214
international relations                 1046
health and environment                   817
business and economics                   681
sports                                   608
science and technology                   475
arts and culture                         353
other current events                      15
religion and politics                      6
entertainment                              3
culture and entertainment                  1
Name: count, dtype: int64

In [19]:
cleaned_df.head()

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."

In [20]:
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture and entertainment", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture and society", "other") 
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace(",environment,", ",other,") 
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("religion", 'other')
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("culture & entertainment", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("other current events", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace("other and politics", "other")
cleaned_df['topic_split'] = cleaned_df['topic_split'].str.replace(",entertainment", ",other")

#cleaned_df.topic_split = cleaned_df.topic_split.str.replace("", ",other,")

In [31]:
cleaned_df = cleaned_df[~cleaned_df.topic_split.str.contains("other", na=False)]
cleaned_df

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...,...,...
1689,1689,1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,1690,1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,1691,1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,1692,1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,1693,1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [32]:

topic_counts = (
    cleaned_df["topic_split"]
    .str.split(",")
    .explode()
    .str.strip()
    .value_counts()
)

print(topic_counts)

topic_split
armed conflicts and attacks             1587
law and crime and politics              1389
disasters and accidents                 1374
politics and elections and economics    1198
international relations                 1035
health and environment                   813
business and economics                   671
sports                                   596
science and technology                   462
arts and culture                         344
Name: count, dtype: int64

In [33]:
cleaned_df

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...,...,...
1689,1689,1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,1690,1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,1691,1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,1692,1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,1693,1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [34]:
X = cleaned_df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'date', 'topic_split'],axis=1) 
y = cleaned_df.topic_split

In [35]:
X

                                           text_cleaned
0     War in Afghanistan  2001 2021    2021 Afghanis...
1     Russo Ukrainian War   2022 Russian invasion of...
2     In  India   a new  income tax  law comes into ...
3     Israel Hamas war   World Central Kitchen drone...
4     Middle Eastern crisis   Gaza war   Israeli inv...
...                                                 ...
1689  Afghanistan conflict   2021 evacuation from Af...
1690  Russo Ukrainian War   2022 Russian invasion of...
1691  Russian invasion of Ukraine   Zaporizhzhia Nuc...
1692  Russian invasion of Ukraine   Eastern Ukraine ...
1693  Middle Eastern crisis   Gaza war   2025 Gaza C...

[1669 rows x 1 columns]

In [36]:
X.text_cleaned.str.lower()

0       war in afghanistan  2001 2021    2021 afghanis...
1       russo ukrainian war   2022 russian invasion of...
2       in  india   a new  income tax  law comes into ...
3       israel hamas war   world central kitchen drone...
4       middle eastern crisis   gaza war   israeli inv...
                              ...
1689    afghanistan conflict   2021 evacuation from af...
1690    russo ukrainian war   2022 russian invasion of...
1691    russian invasion of ukraine   zaporizhzhia nuc...
1692    russian invasion of ukraine   eastern ukraine ...
1693    middle eastern crisis   gaza war   2025 gaza c...
Name: text_cleaned, Length: 1669, dtype: object

In [37]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import MultiLabelBinarizer
from iterstrat.ml_stratifiers import MultilabelStratifiedShuffleSplit

def get_minority_samples(X, y, ir_threshold=1.0):
    """Get samples belonging to minority labels (below mean IR)."""
    n_samples = y.shape[0]
    label_counts = y.sum(axis=0)
    mean_ir = np.mean(label_counts)
    
    minority_labels = np.where(label_counts < mean_ir)[0]
    minority_mask = y[:, minority_labels].sum(axis=1) > 0
    
    return X[minority_mask], y[minority_mask]

def mlsmote(X, y, n_samples=500, k_neighbors=5, random_state=42):
    """
    MLSMOTE: Synthetic Minority Oversampling for Multilabel data
    
    Parameters:
        X: np.ndarray — feature matrix (numeric)
        y: np.ndarray — binary label matrix (n_samples x n_labels)
        n_samples: int — number of synthetic samples to generate
        k_neighbors: int — number of nearest neighbors to use
    
    Returns:
        X_resampled, y_resampled (originals + synthetic)
    """
    rng = np.random.default_rng(random_state)
    
    # Focus on minority samples
    X_min, y_min = get_minority_samples(X, y)
    
    if len(X_min) < k_neighbors + 1:
        print(f"Warning: only {len(X_min)} minority samples, reducing k")
        k_neighbors = len(X_min) - 1
    
    # Fit KNN on minority samples
    knn = NearestNeighbors(n_neighbors=k_neighbors + 1)  # +1 because sample is own neighbor
    knn.fit(X_min)
    
    synthetic_X = []
    synthetic_y = []
    
    for _ in range(n_samples):
        # Pick a random minority sample as reference
        idx = rng.integers(0, len(X_min))
        x_ref = X_min[idx]
        y_ref = y_min[idx]
        
        # Find its k nearest neighbors
        _, neighbor_idxs = knn.kneighbors([x_ref])
        neighbor_idxs = neighbor_idxs[0][1:]  # exclude self
        
        # Pick a random neighbor
        nn_idx = rng.choice(neighbor_idxs)
        x_neighbor = X_min[nn_idx]
        y_neighbor = y_min[nn_idx]
        
        # Interpolate features
        gap = rng.random()
        x_synthetic = x_ref + gap * (x_neighbor - x_ref)
        
        # Union of labels (standard MLSMOTE label generation)
        y_synthetic = np.logical_or(y_ref, y_neighbor).astype(int)
        
        synthetic_X.append(x_synthetic)
        synthetic_y.append(y_synthetic)
    
    X_resampled = np.vstack([X, np.array(synthetic_X)])
    y_resampled = np.vstack([y, np.array(synthetic_y)])
    
    return X_resampled, y_resampled

In [38]:
mlb = MultiLabelBinarizer() 


y_lists = cleaned_df['topic_split'].apply(lambda x: [i.strip() for i in x.split(',')])

y_mlb = mlb.fit_transform(y_lists)

In [39]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'disasters and accidents',
       'health and environment', 'international relations',
       'law and crime and politics',
       'politics and elections and economics', 'science and technology',
       'sports'], dtype=object)

In [40]:
len(mlb.classes_)

10

In [41]:
y_mlb

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0]])

In [42]:
cleaned_df.topic_split

0       armed conflicts and attacks,arts and culture,b...
1       armed conflicts and attacks,disasters and acci...
2       business and economics,disasters and accidents...
3       armed conflicts and attacks,disasters and acci...
4       armed conflicts and attacks,disasters and acci...
                              ...
1689    armed conflicts and attacks,arts and culture,b...
1690    armed conflicts and attacks,disasters and acci...
1691    armed conflicts and attacks,arts and culture,l...
1692    armed conflicts and attacks,business and econo...
1693    armed conflicts and attacks,disasters and acci...
Name: topic_split, Length: 1669, dtype: object

In [43]:
y

0       armed conflicts and attacks,arts and culture,b...
1       armed conflicts and attacks,disasters and acci...
2       business and economics,disasters and accidents...
3       armed conflicts and attacks,disasters and acci...
4       armed conflicts and attacks,disasters and acci...
                              ...
1689    armed conflicts and attacks,arts and culture,b...
1690    armed conflicts and attacks,disasters and acci...
1691    armed conflicts and attacks,arts and culture,l...
1692    armed conflicts and attacks,business and econo...
1693    armed conflicts and attacks,disasters and acci...
Name: topic_split, Length: 1669, dtype: object

In [44]:
y_mlb

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0]])

In [45]:
mlb.classes_

array(['armed conflicts and attacks', 'arts and culture',
       'business and economics', 'disasters and accidents',
       'health and environment', 'international relations',
       'law and crime and politics',
       'politics and elections and economics', 'science and technology',
       'sports'], dtype=object)

In [46]:
y_mlb

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       ...,
       [1, 1, 0, ..., 1, 0, 1],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 1, 0]])

In [47]:
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [48]:
# getting the stop words

stop_words = list(set(stopwords.words('english')))

In [49]:
X

                                           text_cleaned
0     War in Afghanistan  2001 2021    2021 Afghanis...
1     Russo Ukrainian War   2022 Russian invasion of...
2     In  India   a new  income tax  law comes into ...
3     Israel Hamas war   World Central Kitchen drone...
4     Middle Eastern crisis   Gaza war   Israeli inv...
...                                                 ...
1689  Afghanistan conflict   2021 evacuation from Af...
1690  Russo Ukrainian War   2022 Russian invasion of...
1691  Russian invasion of Ukraine   Zaporizhzhia Nuc...
1692  Russian invasion of Ukraine   Eastern Ukraine ...
1693  Middle Eastern crisis   Gaza war   2025 Gaza C...

[1669 rows x 1 columns]

In [50]:
vectorizer = TfidfVectorizer(max_features=500, stop_words=stop_words)
X = vectorizer.fit_transform(X['text_cleaned'].str.lower()).toarray()  # must be dense
y = y_mlb
# --- Stratified split BEFORE resampling ---
splitter = MultilabelStratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in splitter.split(X, y):
    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

# --- Check label distribution improved ---
before = y_train.sum(axis=0)
after = y_train_res.sum(axis=0)
comparison = pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_)
print(comparison)

Before: 1327 samples
After:  1627 samples
                                      before  after
armed conflicts and attacks             1263   1560
arts and culture                         275    411
business and economics                   537    753
disasters and accidents                 1095   1378
health and environment                   650    856
international relations                  828   1086
law and crime and politics              1111   1403
politics and elections and economics     958   1232
science and technology                   370    516
sports                                   477    668

In [51]:
X_train_res, y_train_res = mlsmote(X_train, y_train, n_samples=300, k_neighbors=5)

print(f"Before: {X_train.shape[0]} samples")
print(f"After:  {X_train_res.shape[0]} samples")

# --- Check label distribution improved ---
before = y_train.sum(axis=0)
after = y_train_res.sum(axis=0)
comparison = pd.DataFrame({'before': before, 'after': after}, index=mlb.classes_)
print(comparison)

Before: 1327 samples
After:  1627 samples
                                      before  after
armed conflicts and attacks             1263   1560
arts and culture                         275    411
business and economics                   537    753
disasters and accidents                 1095   1378
health and environment                   650    856
international relations                  828   1086
law and crime and politics              1111   1403
politics and elections and economics     958   1232
science and technology                   370    516
sports                                   477    668

In [52]:
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
# trying a one vs rest

from sklearn.multiclass import OneVsRestClassifier

In [53]:
model = OneVsRestClassifier(XGBClassifier())

model.fit(X_train_res, y_train_res)

OneVsRestClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                            callbacks=None,
                                            colsample_bylevel=None,
                                            colsample_bynode=None,
                                            colsample_bytree=None, device=None,
                                            early_stopping_rounds=None,
                                            enable_categorical=False,
                                            eval_metric=None,
                                            feature_types=None,
                                            feature_weights=None, gamma=None,
                                            grow_policy=None,
                                            importance_type=None,
                                            interaction_constraints=None,
                                            learning_rate=None, max_bin=None,
                                            max_cat_threshold=None,
                                            max_cat_to_onehot=None,
                                            max_delta_step=None, max_depth=None,
                                            max_leaves=None,
                                            min_child_weight=None, missing=nan,
                                            monotone_constraints=None,
                                            multi_strategy=None,
                                            n_estimators=None, n_jobs=None,
                                            num_parallel_tree=None, ...))

In [54]:
pred = model.predict(X_test)

# metrics

In [55]:
from sklearn.metrics import accuracy_score, f1_score, precision_recall_curve

In [56]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()

In [57]:
MR

0.14619883040935672

In [58]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [59]:
loss01

0.8538011695906432

In [60]:
accuracy_score(pred, y_test)

0.14619883040935672

In [61]:
f1_score(y_test, pred, average='micro')

0.8334223171382809

In [62]:
from sklearn.metrics import f1_score
f1_score(y_test, pred, average='macro')

0.7158994329980402

In [63]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

0.8132471546427951

In [64]:
from sklearn.model_selection import cross_val_score

In [65]:
cross_val_score(model, X, y, scoring='f1_macro', cv=5)

array([0.70705411, 0.73922028, 0.73297105, 0.72746071, 0.69687288])

In [66]:
# tuning the model

In [67]:
from sklearn.model_selection import GridSearchCV
from skopt import BayesSearchCV
from skopt.space import Real, Categorical, Integer

In [317]:


opt = BayesSearchCV(
    OneVsRestClassifier(XGBClassifier()),

                        
                        
    {
        'estimator__n_estimators': Integer(10, 1000, prior='log-uniform'),
        'estimator__max_depth': Integer(10, 100, prior='log-uniform'),
        'estimator__eta': Real(0.1, 0.3),
        
    },
    n_iter=32,
    random_state=0
)

_ = opt.fit(X_train_res, y_train_res)

In [319]:
# metrics for bayes search

pred = opt.predict(X_test)
print (f"accuracy: {accuracy_score(y_true=y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=y_test, average='macro')}")

accuracy: 0.1457725947521866
f1 score weighted: 0.8201170121183478
f1 score micro: 0.839622641509434
f1 score macro: 0.6654519083283263

In [70]:
param_grid = {
    'estimator__n_estimators': [50, 100, 200],
    'estimator__max_depth': [20, 30, 40],
    'estimator__eta': [0.1, 0.3],

}

# Run grid search
grid_search = GridSearchCV(
    estimator=OneVsRestClassifier(XGBClassifier()),
    param_grid=param_grid,
    scoring='f1_macro',       # use macro F1 for imbalanced multilabel
    cv=5,
    n_jobs=-1,                # use all CPU cores
    verbose=2
)

grid_search.fit(X_train_res, y_train_res)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=50; total time= 1.5min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=100; total time= 2.0min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=100; total time= 2.1min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=100; total time= 2.1min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=100; total time= 1.6min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=100; total time= 1.8min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=50; total time= 1.3min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=200; total time= 2.3min
[CV] END estimator__eta=0.1, estimator__max_depth=20, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=50; total time= 1.6min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=50; total time= 1.6min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=50; total time= 1.5min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=100; total time= 2.0min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=100; total time= 2.1min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=100; total time= 2.0min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=100; total time= 2.1min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=100; total time= 1.8min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=200; total time= 2.3min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=200; total time= 2.3min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=50; total time= 1.4min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=50; total time= 1.5min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=50; total time= 1.5min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=200; total time= 2.4min
[CV] END estimator__eta=0.1, estimator__max_depth=30, estimator__n_estimators=200; total time= 2.5min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=50; total time= 1.7min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=50; total time= 1.6min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=100; total time= 2.0min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=100; total time= 1.9min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=100; total time= 1.9min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=100; total time= 1.9min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=100; total time= 1.6min
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=50; total time=  37.1s
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=200; total time= 2.2min
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=50; total time=  41.0s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=50; total time=  42.4s
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=200; total time= 2.2min
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=200; total time= 2.2min
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=50; total time=  40.5s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=50; total time=  37.2s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=100; total time=  47.0s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=100; total time=  47.8s
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=200; total time= 2.0min
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=100; total time=  47.6s
[CV] END estimator__eta=0.1, estimator__max_depth=40, estimator__n_estimators=200; total time= 2.0min
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=100; total time=  45.9s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=100; total time=  45.3s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=200; total time=  56.6s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=200; total time=  58.2s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=50; total time=  39.7s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=50; total time=  39.8s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=50; total time=  39.0s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=200; total time=  59.4s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=200; total time=  58.0s
[CV] END estimator__eta=0.3, estimator__max_depth=20, estimator__n_estimators=200; total time=  59.7s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=50; total time=  38.3s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=50; total time=  34.4s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=100; total time=  49.4s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=100; total time=  49.7s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=100; total time=  48.8s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=100; total time=  48.1s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=100; total time=  45.2s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=200; total time=  58.2s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=50; total time=  34.2s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=200; total time= 1.0min
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=50; total time=  36.3s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=50; total time=  37.1s
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=200; total time= 1.0min
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=200; total time= 1.0min
[CV] END estimator__eta=0.3, estimator__max_depth=30, estimator__n_estimators=200; total time= 1.0min
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=50; total time=  36.9s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=50; total time=  34.4s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=100; total time=  45.1s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=100; total time=  46.8s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=100; total time=  44.8s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=100; total time=  45.3s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=100; total time=  38.7s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=200; total time=  47.8s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=200; total time=  46.1s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=200; total time=  44.0s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=200; total time=  37.6s
[CV] END estimator__eta=0.3, estimator__max_depth=40, estimator__n_estimators=200; total time=  33.9s

GridSearchCV(cv=5,
             estimator=OneVsRestClassifier(estimator=XGBClassifier(base_score=None,
                                                                   booster=None,
                                                                   callbacks=None,
                                                                   colsample_bylevel=None,
                                                                   colsample_bynode=None,
                                                                   colsample_bytree=None,
                                                                   device=None,
                                                                   early_stopping_rounds=None,
                                                                   enable_categorical=False,
                                                                   eval_metric=None,
                                                                   feature_types=None,
                                                                   feature_weights=None,
                                                                   gamma=None,
                                                                   grow_policy=None,
                                                                   importance_type=No...
                                                                   max_cat_to_onehot=None,
                                                                   max_delta_step=None,
                                                                   max_depth=None,
                                                                   max_leaves=None,
                                                                   min_child_weight=None,
                                                                   missing=nan,
                                                                   monotone_constraints=None,
                                                                   multi_strategy=None,
                                                                   n_estimators=None,
                                                                   n_jobs=None,
                                                                   num_parallel_tree=None, ...)),
             n_jobs=-1,
             param_grid={'estimator__eta': [0.1, 0.3],
                         'estimator__max_depth': [20, 30, 40],
                         'estimator__n_estimators': [50, 100, 200]},
             scoring='f1_macro', verbose=2)

In [376]:
from sklearn.metrics import hamming_loss, label_ranking_loss

In [377]:
pred = grid_search.predict(X_test)
print (f"accuracy: {accuracy_score(y_true=y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=y_test, average='macro')}")
print (f"hamming loss: {hamming_loss(y_true=y_test, y_pred=pred)}")
print (f"label ranking loss: {label_ranking_loss(y_true=y_test, y_pred=pred)}")

accuracy: 0.1457725947521866
f1 score weighted: 0.822388376170596
f1 score micro: 0.840146750524109
f1 score macro: 0.671215369114747
hamming loss: 0.1616750596342433

TypeError: missing a required argument: 'y_score'

In [309]:
f1_score(y_pred=pred, y_true=y_test, average='weighted')

0.822388376170596

In [310]:
f1_score(y_pred=pred, y_true=y_test, average='macro')

0.671215369114747

In [311]:
f1_score(y_pred=pred, y_true=y_test, average='micro')

0.840146750524109

In [281]:
# metrics 
MR = np.all(pred == y_test, axis=1).mean()
MR

0.15160349854227406

In [282]:
loss01 = np.any(y_test != pred, axis=1).mean()

In [283]:
loss01

0.8483965014577259

In [322]:
import joblib 
joblib.dump(grid_search, 'news_topic_classifier.pkl')

['news_topic_classifier.pkl']

In [323]:
joblib.dump(mlb, "mlb.pkl")

['mlb.pkl']

In [324]:
joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

['tfidf_vectorizer.pkl']

# trying a neural network

In [14]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
import joblib

In [15]:
mlb = joblib.load("mlb.pkl")

In [16]:
cleaned_df

,Unnamed: 0.1,Unnamed: 0,date,text_cleaned,topic_split
0,0,0,"April 1, 2021",War in Afghanistan 2001 2021 2021 Afghanis...,"armed conflicts and attacks,arts and culture,b..."
1,1,1,"April 1, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
2,2,2,"April 1, 2023",In India a new income tax law comes into ...,"business and economics,disasters and accidents..."
3,3,3,"April 1, 2024",Israel Hamas war World Central Kitchen drone...,"armed conflicts and attacks,disasters and acci..."
4,4,4,"April 1, 2025",Middle Eastern crisis Gaza war Israeli inv...,"armed conflicts and attacks,disasters and acci..."
...,...,...,...,...,...
1689,1689,1689,"September 9, 2021",Afghanistan conflict 2021 evacuation from Af...,"armed conflicts and attacks,arts and culture,b..."
1690,1690,1690,"September 9, 2022",Russo Ukrainian War 2022 Russian invasion of...,"armed conflicts and attacks,disasters and acci..."
1691,1691,1691,"September 9, 2023",Russian invasion of Ukraine Zaporizhzhia Nuc...,"armed conflicts and attacks,arts and culture,l..."
1692,1692,1692,"September 9, 2024",Russian invasion of Ukraine Eastern Ukraine ...,"armed conflicts and attacks,business and econo..."
1693,1693,1693,"September 9, 2025",Middle Eastern crisis Gaza war 2025 Gaza C...,"armed conflicts and attacks,disasters and acci..."

In [17]:
X = cleaned_df['text_cleaned']
y = cleaned_df.topic_split.str.split(",")

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2)

In [23]:
Y_train = mlb.transform(Y_train)
Y_test = mlb.transform(Y_test)

/opt/miniconda3/envs/news_project/lib/python3.12/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) [0, 1] will be ignored
  warnings.warn(

In [24]:
batch_size = 32

In [42]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.model_selection import train_test_split
import numpy as np

# ── Tokenisation ──────────────────────────────────────────────────────────────
VOCAB_SIZE = 5000
MAX_LEN    = 200
EMBED_DIM  = 64

tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

# Then proceed as normal
tokenizer = Tokenizer(num_words=VOCAB_SIZE, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

# --------------------
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq  = tokenizer.texts_to_sequences(X_test)

X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding="post", truncating="post")
X_test_pad  = pad_sequences(X_test_seq,  maxlen=MAX_LEN, padding="post", truncating="post")

# ── Model ─────────────────────────────────────────────────────────────────────
NUM_LABELS = Y_train.shape[1]   # inferred from your label matrix

model = Sequential([
    Embedding(input_dim=VOCAB_SIZE, output_dim=EMBED_DIM, input_length=MAX_LEN),
    Bidirectional(LSTM(128, return_sequences=True)),  # reads text both ways
    Dropout(0.3),
    LSTM(128),
    Dropout(0.3),
    Dense(128, activation="relu"),
    Dense(11, activation="sigmoid"),          # sigmoid for multi-label
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",   # correct loss for multi-label
    metrics=["accuracy"],
)

model.summary()

# ── Callbacks ─────────────────────────────────────────────────────────────────
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=3,               # stop if val_loss doesn't improve for 3 epochs
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,               # halve the learning rate on plateau
    patience=2,
    min_lr=1e-6,
    verbose=1
)

# ── Training ──────────────────────────────────────────────────────────────────
history = model.fit(
    X_train_pad, Y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_test_pad, Y_test),
    callbacks=[early_stop, reduce_lr],
    verbose=1,
)

# ── Evaluation ────────────────────────────────────────────────────────────────
loss, accuracy = model.evaluate(X_test_pad, Y_test, verbose=0)
print(f"Test loss:     {loss:.4f}")
print(f"Test accuracy: {accuracy:.4f}")

# ── Save ──────────────────────────────────────────────────────────────────────
model.save("data/lstm_classifier.h5")
joblib.dump(tokenizer, "data/lstm_tokenizer.pkl")
print("Model and tokenizer saved.")

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_4 (Bidirectional) │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
43/43 ━━━━━━━━━━━━━━━━━━━━ 11s 160ms/step - accuracy: 0.0221 - loss: 0.1250 - val_accuracy: 0.0029 - val_loss: 6.3242 - learning_rate: 0.0010
Epoch 2/20
43/43 ━━━━━━━━━━━━━━━━━━━━ 6s 135ms/step - accuracy: 0.0369 - loss: 9.1375e-06 - val_accuracy: 0.0029 - val_loss: 6.5865 - learning_rate: 0.0010
Epoch 3/20
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.0377 - loss: 7.0510e-06
Epoch 3: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
43/43 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.0413 - loss: 6.9835e-06 - val_accuracy: 0.0029 - val_loss: 6.6191 - learning_rate: 0.0010
Epoch 4/20
43/43 ━━━━━━━━━━━━━━━━━━━━ 6s 132ms/step - accuracy: 0.0391 - loss: 7.0612e-06 - val_accuracy: 0.0029 - val_loss: 6.6356 - learning_rate: 5.0000e-04

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Test loss:     6.3242
Test accuracy: 0.0029
Model and tokenizer saved.

In [43]:
# metrics 
from sklearn.metrics import hamming_loss, f1_score, accuracy_score

In [44]:
X_test_seq = tokenizer.texts_to_sequences(X_test)
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding="post", truncating="post")

In [45]:
prob = model.predict(X_test_pad)
pred = (prob >= 0.5).astype(int)
print (f"accuracy: {accuracy_score(y_true=Y_test, y_pred=pred)}")
print (f"f1 score weighted: {f1_score(y_pred=pred, y_true=Y_test, average='weighted')}")
print (f"f1 score micro: {f1_score(y_pred=pred, y_true=Y_test, average='micro')}")
print (f"f1 score macro: {f1_score(y_pred=pred, y_true=Y_test, average='macro')}")

11/11 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step
accuracy: 0.0
f1 score weighted: 0.0
f1 score micro: 0.0
f1 score macro: 0.0

In [40]:
pred

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])